# Business Goal/Outcome

## Goal
Give a realtor like Jeanine a data-backed answer to the question every seller asks ("What's my home worth, and how long will it take?") and every buyer asks ("Do I have room to negotiate?"), specific to the zip they're standing in.

## Outcomes
- Realtor can price the seller correctly in listing appts 
- Aide buyer consolutations and negotiation strategy
- Help with prospecting and knowing which zips to farm
- Data to feed market update content
- Help relay market expertise

# Research Question
Where in Orlando have sellers lost leverage since 2023, and where do they still have it?

# Hypothesis

**H1: New construction hurt resale sellers most.**  
		In 34787 and 32712, price cut share and days on market will have risen more than the metro average since 2022, because builders' incentives pull buyers away from resale homes.  
		_Rejected if:_ both zips' increases are at or below the metro average.


**H2: Windermere held up.**  
		In 34786, the leverage score will have dropped less than the metro average since 2022, because scarce lakefront and large-lot homes and less rate-sensitive buyers protect sellers.  
		_Rejected if:_ 34786's drop is at or above the metro average. If that happens, the Horizon West portion of the zip may be dragging it down.


**H3: Affordable zips**
 34761 and 32703 will have lost less leverage than 34787 and 32712, because they have less new-construction competition. _Rejected if:_ their drop is the same as or larger than the growth zips'.

# Bring in Data For Prep

In [5]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [6]:
historical = pd.read_csv('/Users/medhasubramaniyan/Desktop/GitHub_Repos/orlando-seller-leverage-analysis/data/RDC_Inventory_Core_Metrics_Zip_History.csv')
historical

,month_date_yyyymm,postal_code,zip_name,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,median_days_on_market_mm,median_days_on_market_yy,new_listing_count,new_listing_count_mm,new_listing_count_yy,price_increased_count,price_increased_count_mm,price_increased_count_yy,price_increased_share,price_increased_share_mm,price_increased_share_yy,price_reduced_count,price_reduced_count_mm,price_reduced_count_yy,price_reduced_share,price_reduced_share_mm,price_reduced_share_yy,pending_listing_count,pending_listing_count_mm,pending_listing_count_yy,median_listing_price_per_square_foot,median_listing_price_per_square_foot_mm,median_listing_price_per_square_foot_yy,median_square_feet,median_square_feet_mm,median_square_feet_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag
0,202608,74003,"bartlesville, ok",150000.0,0.0000,0.0714,45,-0.0722,0.0714,70.0,0.2335,0.4000,16,0.1429,0.3333,0,NaN,NaN,0.0000,0.0,0.0000,20.0,0.2500,0.0000,0.2174,0.0591,-0.0725,26.0,0.0000,0.3684,103.0,0.0093,0.0731,1377.0,0.0025,-0.1179,208058.0,-0.0086,0.0436,71,-0.0596,0.1639,0.5778,0.0417,0.1254,0.0
1,202608,61353,"paw paw, il",294450.0,0.0865,0.0711,7,0.2727,0.4000,27.0,-0.2895,-0.7823,4,-0.3333,NaN,0,NaN,NaN,0.0000,0.0,0.0000,0.0,-1.0000,NaN,0.0000,-0.4857,0.0000,2.0,0.5000,-0.5000,138.0,-0.0381,-0.0657,2092.0,0.0241,-0.1285,432643.0,0.2654,0.2023,8,0.3333,0.1429,0.2143,0.0325,-0.3857,1.0
2,202608,35765,"pisgah, al",307950.0,0.0448,0.1322,15,0.0345,0.5000,105.0,-0.0024,1.3864,0,-1.0000,NaN,0,NaN,NaN,0.0000,0.0,0.0000,0.0,NaN,-1.0000,0.0000,0.0000,-0.3200,2.0,1.0000,0.0000,145.0,-0.0329,-0.1275,1948.0,0.0000,0.2074,312969.0,-0.0256,-0.1669,18,0.1613,0.3846,0.1333,0.0644,-0.0667,1.0
3,202608,21664,"secretary, md",349900.0,0.0294,0.0218,2,0.3333,-0.5000,54.0,-0.0270,0.1739,0,NaN,NaN,0,NaN,NaN,0.0000,0.0,0.0000,0.0,NaN,NaN,0.0000,0.0000,0.0000,0.0,-1.0000,-1.0000,191.0,-0.0163,0.1149,1830.0,0.0404,0.4338,349900.0,0.0294,0.1915,2,-0.3333,-0.5000,0.0000,-0.6667,-0.2500,0.0
4,202608,37221,"nashville, tn",519900.0,-0.0295,-0.0877,235,0.0129,0.0930,64.0,0.0802,-0.2000,80,-0.2000,0.0000,0,NaN,-1.0,0.0000,0.0,-0.0097,104.0,0.1818,0.4444,0.2708,0.0687,0.0969,77.0,-0.1979,-0.2300,252.0,-0.0174,-0.0443,2009.0,-0.0025,-0.0995,742763.0,0.0067,0.0582,312,-0.0473,-0.0064,0.3277,-0.0861,-0.1375,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3452028,201607,8828,"helmetta, nj",218000.0,NaN,NaN,22,NaN,NaN,67.0,NaN,NaN,4,NaN,NaN,0,NaN,NaN,0.0000,NaN,NaN,2.0,NaN,NaN,0.0769,NaN,NaN,1.0,NaN,NaN,159.0,NaN,NaN,1198.0,NaN,NaN,243027.0,NaN,NaN,22,NaN,NaN,0.0455,NaN,NaN,NaN
3452029,201607,30536,"ellijay, ga",249350.0,NaN,NaN,128,NaN,NaN,86.0,NaN,NaN,26,NaN,NaN,2,NaN,NaN,0.0128,NaN,NaN,34.0,NaN,NaN,0.2257,NaN,NaN,2.0,NaN,NaN,125.0,NaN,NaN,2032.0,NaN,NaN,309281.0,NaN,NaN,128,NaN,NaN,0.0118,NaN,NaN,NaN
3452030,201607,37863,"pigeon forge, tn",224750.0,NaN,NaN,189,NaN,NaN,115.0,NaN,NaN,16,NaN,NaN,0,NaN,NaN,0.0000,NaN,NaN,14.0,NaN,NaN,0.0589,NaN,NaN,39.0,NaN,NaN,150.0,NaN,NaN,1500.0,NaN,NaN,283587.0,NaN,NaN,226,NaN,NaN,0.2042,NaN,NaN,NaN
3452031,201607,32097,"yulee, fl",231973.0,NaN,NaN,150,NaN,NaN,69.0,NaN,NaN,58,NaN,NaN,22,NaN,NaN,0.0606,NaN,NaN,24.0,NaN,NaN,0.0678,NaN,NaN,104.0,NaN,NaN,108.0,NaN,NaN,2094.0,NaN,NaN,324656.0,NaN,NaN,252,NaN,NaN,0.6923,NaN,NaN,NaN
3452032,201607,59064,"pompeys pillar, mt",199500.0,NaN,NaN,1,NaN,NaN,14.0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0.0000,NaN,NaN,0.0,NaN,NaN,0.0000,NaN,NaN,1.0,NaN,NaN,88.0,NaN,NaN,2280.0,NaN,NaN,199500.0,NaN,NaN,1,NaN,NaN,1.0000,NaN,NaN,NaN

In [7]:
august = pd.read_csv('/Users/medhasubramaniyan/Desktop/GitHub_Repos/orlando-seller-leverage-analysis/data/RDC_Inventory_Core_Metrics_Zip.csv')
august

,month_date_yyyymm,postal_code,zip_name,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,median_days_on_market_mm,median_days_on_market_yy,new_listing_count,new_listing_count_mm,new_listing_count_yy,price_increased_count,price_increased_count_mm,price_increased_count_yy,price_increased_share,price_increased_share_mm,price_increased_share_yy,price_reduced_count,price_reduced_count_mm,price_reduced_count_yy,price_reduced_share,price_reduced_share_mm,price_reduced_share_yy,pending_listing_count,pending_listing_count_mm,pending_listing_count_yy,median_listing_price_per_square_foot,median_listing_price_per_square_foot_mm,median_listing_price_per_square_foot_yy,median_square_feet,median_square_feet_mm,median_square_feet_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag
0,202608,78956,"schulenburg, tx",314000.0,-0.1253,0.0502,28,0.1200,0.4000,124.0,-0.0294,1.3396,0,-1.0000,-1.0,0,NaN,NaN,0.0,0.0,0.0,12.0,0.5000,NaN,0.2857,0.0413,0.2857,5.0,0.4286,0.2500,167.0,-0.0139,-0.0169,2113.0,-0.0540,0.0581,410433.0,-0.0986,0.2020,32,0.1228,0.3913,0.1786,0.0386,-0.0214,1
1,202608,30535,"demorest, ga",415000.0,-0.0259,0.0038,55,-0.0090,0.4865,90.0,0.3162,1.0341,20,-0.3333,0.0,0,NaN,NaN,0.0,0.0,0.0,16.0,0.3333,0.3333,0.1633,0.0402,-0.0999,14.0,-0.2632,0.2727,183.0,0.0197,-0.0597,2665.0,0.0744,0.1550,461853.0,-0.0132,0.0613,68,-0.0933,0.4167,0.2545,-0.0878,-0.0428,1
2,202608,83316,"buhl, id",510000.0,0.0000,0.2146,45,-0.0110,-0.0816,79.0,0.0604,-0.0920,12,-0.2500,0.0,0,NaN,NaN,0.0,0.0,0.0,12.0,-0.1429,-0.4000,0.2069,-0.0012,-0.0894,10.0,-0.3548,-0.2857,245.0,-0.0077,0.0134,1970.0,-0.0760,0.0221,699305.0,-0.0023,0.2881,55,-0.0833,-0.1129,0.2222,-0.1184,-0.0635,0
3,202608,94806,"san pablo, ca",577500.0,0.0226,-0.0077,71,0.2034,-0.1013,38.0,-0.1508,-0.0843,36,0.2857,0.0,0,NaN,NaN,0.0,0.0,0.0,24.0,1.0000,0.0000,0.1951,0.0919,0.0432,22.0,-0.2281,-0.3529,387.0,0.0181,-0.1229,1312.0,0.0135,0.0492,574916.0,0.0050,-0.0158,91,0.0581,-0.1947,0.3099,-0.1732,-0.1205,0
4,202608,37820,"new market, tn",735000.0,0.0426,0.4703,23,0.1500,0.0455,57.0,0.0411,-0.1094,4,-0.5000,0.0,0,NaN,NaN,0.0,0.0,0.0,8.0,0.0000,-0.3333,0.1509,-0.1013,-0.1824,7.0,0.0769,-0.3636,262.0,0.0060,0.0535,2714.0,-0.0058,0.2730,771742.0,-0.0668,0.5105,29,0.1154,-0.1714,0.3043,-0.0207,-0.1957,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29046,202608,50546,"havelock, ia",265500.0,0.0000,0.0215,1,0.0000,0.0000,81.0,0.6364,0.0658,0,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,0.0000,0.0000,0.0000,1.0,NaN,0.0000,250.0,0.0000,0.0215,1064.0,0.0000,0.0000,265500.0,0.0000,0.0215,2,1.0000,0.0000,1.0000,NaN,0.0000,0
29047,202608,54530,"hawkins, wi",297500.0,0.0000,2.1349,3,-0.1429,0.5000,59.0,1.2056,-0.2436,0,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,0.0000,0.0000,0.0000,2.0,NaN,1.0000,127.0,-0.1443,-0.5646,1443.0,0.4430,1.2494,244967.0,-0.0126,1.5813,4,0.1429,0.3333,0.6667,NaN,0.1667,1
29048,202608,35755,"langston, al",574500.0,0.1011,-0.2584,12,0.0000,1.0000,115.0,0.2568,0.0177,0,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,4.0,1.0000,NaN,0.2857,0.1190,0.2857,1.0,NaN,0.0000,324.0,-0.0056,0.0763,1950.0,-0.1053,-0.4569,725423.0,0.0650,-0.3124,14,0.1667,1.0000,0.0833,NaN,-0.0833,1
29049,202608,69148,"lisco, ne",98700.0,0.0000,-0.7005,1,0.0000,0.0000,107.0,0.2456,5.2647,0,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,0.0000,0.0000,0.0000,1.0,NaN,NaN,40.0,0.0000,-0.7855,2440.0,0.0000,0.3967,98700.0,0.0000,-0.7005,1,0.0000,0.0000,1.0000,NaN,NaN,1
29050,202608,95459,"manchester, ca",1206250.0,-0.1904,0.5366,12,0.0909,0.2000,148.0,0.2156,0.4300,0,NaN,-1.0,0,NaN,NaN,0.0,0.0,0.0,0.0,-1.0000,NaN,0.0000,-0.5455,0.0000,1.0,NaN,0.0000,430.0,-0.0670,-0.2137,1678.0,-0.0868,0.0102,2114242.0,-0.0613,0.0235,12,0.0909,0.0909,0.0833,NaN,-0.0167,1

## Filter the national data down to Florida, Central Florida, and Orlando (August 2026, and Historical)

In [8]:
current_data = august.copy()
past_data = historical.copy()

In [9]:
# greater central forida zips 
orlando_orange_county = [
    "32801", "32803", "32804", "32805", "32806", "32808", "32810",
    "32807", "32817", "32826", "32819", "32828", "32827", "32832", 
    "32835", "32703", "32704", "32712", "34761", "34787", "34786"
]
orlando_orange_county = list(map(int, orlando_orange_county))

seminole_county = [
    "32701", "32714", "32750", "32779", "32746", "32771", 
    "32772", "32773", "32707", "32708", "32765", "32766"
]
seminole_county = list(map(int, seminole_county))

osceola_county = [
    "34741", "34743", "34744", "34746", "34747", "34758",
    "34769", "34770", "34771", "34772"
]
osceola_county = list(map(int, osceola_county))

central_fl_tri_county = orlando_orange_county + seminole_county + osceola_county

In [10]:
def filterToFlorida(df):
    '''pass the national level data here to filter just to the state of florida '''
    florida = df.copy()
    florida[['city', 'state']] = florida['zip_name'].str.split(',', expand=True)
    florida['state'] = florida['state'].str.strip()
    florida['city'] = florida['city'].str.strip()
    florida = florida[florida['state'] == 'fl'] #we've filtered down to florida! 
    return florida 

# central_fl = orl[orl['postal_code'].isin(central_fl_tri_county)]
# orl = orl[orl['postal_code'].isin(orlando_orange_county)]
def filterToCentralFlorida(df):
        '''pass the florida level data here to filter just to central florida and further filter to orlando '''
        central_fl_df = df[df['postal_code'].isin(central_fl_tri_county)] 
        orlando_df = central_fl_df[central_fl_df['postal_code'].isin(orlando_orange_county)]
        return central_fl_df, orlando_df

In [11]:

fl_august = filterToFlorida(current_data)  # current florida august data 
fl_historical =  filterToFlorida(past_data) # past florida data 

central_fl_august, orl_august = filterToCentralFlorida(fl_august) #current central florida and orlando data 
central_fl_historical, orl_historical = filterToCentralFlorida(fl_historical) #past central florida and orlando data

### Check to make sure everything has been filtered properly

In [12]:
print(f"---Current Florida State Data--- \n Unique States:{fl_august['state'].unique()}\n Date:{fl_august['month_date_yyyymm'].unique()}\n # of Cities: {fl_august['zip_name'].nunique()}\n")
print(f"---Historical Florida State Data--- \n Unique States:{fl_historical['state'].unique()}\n Date:{fl_historical['month_date_yyyymm'].unique()}\n # of Cities: {fl_historical['zip_name'].nunique()}\n")

---Current Florida State Data---
 Unique States:['fl']
 Date:[202608]
 # of Cities: 418

---Historical Florida State Data---
 Unique States:['fl']
 Date:[202608 202607 202606 202605 202604 202603 202602 202601 202512 202511
 202510 202509 202508 202507 202506 202505 202504 202503 202502 202501
 202412 202411 202410 202409 202408 202407 202406 202405 202404 202403
 202402 202401 202312 202311 202310 202309 202308 202307 202306 202305
 202304 202303 202302 202301 202212 202211 202210 202209 202208 202207
 202206 202205 202204 202203 202202 202201 202112 202111 202110 202109
 202108 202107 202106 202105 202104 202103 202102 202101 202012 202011
 202010 202009 202008 202007 202006 202005 202004 202003 202002 202001
 201912 201911 201910 201909 201908 201907 201906 201905 201904 201903
 201902 201901 201812 201811 201810 201809 201808 201807 201806 201805
 201804 201803 201802 201801 201712 201711 201710 201709 201708 201707
 201706 201705 201704 201703 201702 201701 201612 201611 201610 201609
 201608 201607]
 # of Cities: 429

In [13]:
print(f"---Current Central Florida Data--- \n Unique States:{central_fl_august['state'].unique()}\n Date:{central_fl_august['month_date_yyyymm'].unique()}\n # of Cities: {central_fl_august['zip_name'].nunique()}\n")
print(f"---Historical Central Florida Data--- \n Unique States:{central_fl_historical['state'].unique()}\n Date:{central_fl_historical['month_date_yyyymm'].unique()}\n # of Cities: {central_fl_historical['zip_name'].nunique()}\n")

---Current Central Florida Data---
 Unique States:['fl']
 Date:[202608]
 # of Cities: 14

---Historical Central Florida Data---
 Unique States:['fl']
 Date:[202608 202607 202606 202605 202604 202603 202602 202601 202512 202511
 202510 202509 202508 202507 202506 202505 202504 202503 202502 202501
 202412 202411 202410 202409 202408 202407 202406 202405 202404 202403
 202402 202401 202312 202311 202310 202309 202308 202307 202306 202305
 202304 202303 202302 202301 202212 202211 202210 202209 202208 202207
 202206 202205 202204 202203 202202 202201 202112 202111 202110 202109
 202108 202107 202106 202105 202104 202103 202102 202101 202012 202011
 202010 202009 202008 202007 202006 202005 202004 202003 202002 202001
 201912 201911 201910 201909 201908 201907 201906 201905 201904 201903
 201902 201901 201812 201811 201810 201809 201808 201807 201806 201805
 201804 201803 201802 201801 201712 201711 201710 201709 201708 201707
 201706 201705 201704 201703 201702 201701 201612 201611 201610 201609
 201608 201607]
 # of Cities: 14

In [14]:
print(f"---Current Orlando Data---  \n Unique States:{orl_august['state'].unique()}\n Date:{orl_august['month_date_yyyymm'].unique()}\n # of Cities: {orl_august['zip_name'].nunique()}\n")
print(f"---Historical Orlando Data---  \n Unique States:{orl_historical['state'].unique()}\n Date:{orl_historical['month_date_yyyymm'].unique()}\n # of Cities: {orl_historical['zip_name'].nunique()}\n")

---Current Orlando Data---
 Unique States:['fl']
 Date:[202608]
 # of Cities: 5

---Historical Orlando Data---
 Unique States:['fl']
 Date:[202608 202607 202606 202605 202604 202603 202602 202601 202512 202511
 202510 202509 202508 202507 202506 202505 202504 202503 202502 202501
 202412 202411 202410 202409 202408 202407 202406 202405 202404 202403
 202402 202401 202312 202311 202310 202309 202308 202307 202306 202305
 202304 202303 202302 202301 202212 202211 202210 202209 202208 202207
 202206 202205 202204 202203 202202 202201 202112 202111 202110 202109
 202108 202107 202106 202105 202104 202103 202102 202101 202012 202011
 202010 202009 202008 202007 202006 202005 202004 202003 202002 202001
 201912 201911 201910 201909 201908 201907 201906 201905 201904 201903
 201902 201901 201812 201811 201810 201809 201808 201807 201806 201805
 201804 201803 201802 201801 201712 201711 201710 201709 201708 201707
 201706 201705 201704 201703 201702 201701 201612 201611 201610 201609
 201608 201607]
 # of Cities: 5

### Filter down to zips that Jeanine serves

In [15]:
focus_zips = [34786, 34787, 34761, 32712 , 32703, 32801] #jeanine's target market
alcime = central_fl_historical[central_fl_historical['postal_code'].isin(focus_zips)]
alcime

,month_date_yyyymm,postal_code,zip_name,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,median_days_on_market_mm,median_days_on_market_yy,new_listing_count,new_listing_count_mm,new_listing_count_yy,price_increased_count,price_increased_count_mm,price_increased_count_yy,price_increased_share,price_increased_share_mm,price_increased_share_yy,price_reduced_count,price_reduced_count_mm,price_reduced_count_yy,price_reduced_share,price_reduced_share_mm,price_reduced_share_yy,pending_listing_count,pending_listing_count_mm,pending_listing_count_yy,median_listing_price_per_square_foot,median_listing_price_per_square_foot_mm,median_listing_price_per_square_foot_yy,median_square_feet,median_square_feet_mm,median_square_feet_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag,city,state
8183,202608,32712,"apopka, fl",455000.0,-0.0246,-0.0712,259,0.0058,0.0792,72.0,0.0511,0.1901,72,-0.2800,-0.1000,4,-0.3333,-0.5,0.0080,-0.0034,-0.0104,124.0,0.2917,0.2400,0.2650,0.0797,0.0351,154.0,0.0233,0.3162,207.0,-0.0006,-0.0519,2077.0,0.0000,-0.0699,494250.0,-0.0276,-0.0921,411,0.0074,0.1743,0.5946,0.0101,0.1071,0.0,apopka,fl
9079,202608,34761,"ocoee, fl",438000.0,0.0368,-0.0374,137,0.0186,0.1513,68.0,0.0837,0.1930,44,-0.1200,-0.0833,0,NaN,-1.0,0.0000,0.0000,-0.0161,68.0,0.2593,0.1333,0.2595,0.0620,-0.0071,76.0,0.0000,0.0857,219.0,-0.0029,-0.0401,1915.0,0.0606,-0.0103,465740.0,0.0446,-0.0939,215,0.0190,0.1436,0.5547,-0.0103,-0.0335,0.0,ocoee,fl
17845,202608,34787,"winter garden, fl",590000.0,0.0022,-0.0407,639,-0.0244,-0.0169,72.0,0.0909,0.0000,204,-0.0642,0.1087,8,1.0000,1.0,0.0072,0.0038,0.0031,260.0,0.0078,0.1207,0.2226,0.0166,-0.0081,326.0,-0.0151,0.7814,256.0,0.0029,-0.0187,2204.0,-0.0011,-0.0541,708634.0,-0.0095,-0.0506,960,-0.0264,0.1622,0.5102,0.0048,0.2286,0.0,winter garden,fl
19739,202608,34786,"windermere, fl",1089000.0,-0.0200,0.1204,233,-0.0251,-0.0567,75.0,0.0714,0.1364,56,-0.3171,-0.1250,0,NaN,-1.0,0.0000,0.0000,-0.0099,84.0,-0.0233,0.0000,0.2353,0.0229,0.0165,79.0,0.0128,-0.0482,341.0,-0.0136,0.0983,3211.0,-0.0170,0.0368,2272980.0,-0.0055,0.3265,310,-0.0143,-0.0520,0.3391,0.0127,0.0030,0.0,windermere,fl
19757,202608,32703,"apopka, fl",405000.0,0.0095,0.0387,169,0.0563,-0.0398,66.0,0.0820,0.1000,68,0.1724,0.0000,4,1.0000,0.0,0.0130,0.0077,0.0021,92.0,0.1500,0.0952,0.2779,0.0452,0.0218,97.0,-0.1745,-0.1416,219.0,-0.0118,-0.0087,1844.0,0.0216,0.0395,446249.0,0.0080,0.0266,263,-0.0573,-0.0993,0.5740,-0.1604,-0.0681,0.0,apopka,fl
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3424422,201607,34786,"windermere, fl",641256.0,NaN,NaN,558,NaN,NaN,81.0,NaN,NaN,144,NaN,NaN,24,NaN,NaN,0.0288,NaN,NaN,162.0,NaN,NaN,0.1818,NaN,NaN,156.0,NaN,NaN,183.0,NaN,NaN,3527.0,NaN,NaN,1141180.0,NaN,NaN,709,NaN,NaN,0.2789,NaN,NaN,NaN,windermere,fl
3424815,201607,32703,"apopka, fl",239000.0,NaN,NaN,125,NaN,NaN,43.0,NaN,NaN,88,NaN,NaN,14,NaN,NaN,0.0411,NaN,NaN,38.0,NaN,NaN,0.1074,NaN,NaN,141.0,NaN,NaN,111.0,NaN,NaN,1995.0,NaN,NaN,261231.0,NaN,NaN,266,NaN,NaN,1.1325,NaN,NaN,NaN,apopka,fl
3428521,201607,34787,"winter garden, fl",360305.0,NaN,NaN,397,NaN,NaN,61.0,NaN,NaN,158,NaN,NaN,38,NaN,NaN,0.0495,NaN,NaN,176.0,NaN,NaN,0.2328,NaN,NaN,215.0,NaN,NaN,134.0,NaN,NaN,2811.0,NaN,NaN,428933.0,NaN,NaN,610,NaN,NaN,0.5403,NaN,NaN,NaN,winter garden,fl
3443616,201607,32801,"orlando, fl",332548.0,NaN,NaN,138,NaN,NaN,72.0,NaN,NaN,32,NaN,NaN,0,NaN,NaN,0.0000,NaN,NaN,50.0,NaN,NaN,0.2005,NaN,NaN,62.0,NaN,NaN,260.0,NaN,NaN,1263.0,NaN,NaN,404568.0,NaN,NaN,199,NaN,NaN,0.4457,NaN,NaN,NaN,orlando,fl
3443974,201607,32712,"apopka, fl",298500.0,NaN,NaN,166,NaN,NaN,56.0,NaN,NaN,82,NaN,NaN,12,NaN,NaN,0.0307,NaN,NaN,80.0,NaN,NaN,0.1789,NaN,NaN,151.0,NaN,NaN,114.0,NaN,NaN,2645.0,NaN,NaN,304765.0,NaN,NaN,318,NaN,NaN,0.9066,NaN,NaN,NaN,apopka,fl

In [23]:
import duckdb



conn = duckdb.connect()
fl_zips = ', '.join(fl_historical['postal_code'].astype(str))

In [25]:
redfin = conn.sql(f""" 
                    SELECT * 
                    FROM '/Users/medhasubramaniyan/Desktop/GitHub_Repos/orlando-seller-leverage-analysis/data/redfin_housing_market_monthly_all_zips_2016_Jul_to_2026_Aug.csv' 
                    WHERE CAST("REGION NAME" AS INTEGER) IN ({fl_zips})
                     """).df()

redfin

,LAST UPDATED,FREQUENCY,PERIOD BEGIN,PERIOD END,REGION ID,REGION TYPE,REGION NAME,METRO,HOMES SOLD,HOMES SOLD YOY (%),MEDIAN SALE PRICE NSA ($),MEDIAN SALE PRICE NSA YOY (%),MEDIAN DAYS ON MARKET (DAYS),MEDIAN DAYS ON MARKET YOY (DAYS),AVERAGE SALE TO LIST RATIO (%),AVERAGE SALE TO LIST RATIO YOY (PPTS),SHARE SOLD ABOVE ORIGINAL LIST (%),SHARE SOLD ABOVE ORIGINAL LIST YOY (PPTS),NEW LISTINGS,NEW LISTINGS YOY (%),ACTIVE LISTINGS,ACTIVE LISTINGS YOY (%),INVENTORY,INVENTORY YOY (%),PENDING SALES,PENDING SALES YOY (%),MEDIAN NEW LISTING PRICE ($),MEDIAN NEW LISTING PRICE YOY (%),MEDIAN NEW LISTING PRICE PER SQ.FT. ($),MEDIAN NEW LISTING PRICE PER SQ.FT. YOY (%),MEDIAN SALE PRICE PER SQ.FT. ($),MEDIAN SALE PRICE PER SQ.FT. YOY (%),MONTHS OF SUPPLY,MONTHS OF SUPPLY YOY (%),PERCENT OFF MARKET IN TWO WEEKS (%),PERCENT OFF MARKET IN TWO WEEKS YOY (PPTS)
0,2026-09-03,Rolling 3 Months,2025-08-01,2025-10-31,14215,Zip,33510,"Tampa, FL metro area",77,22.22,365000,8.63,36,13,96.96,-0.45,9.09,-13.13,82,-6.82,165,-2.94,82,-12.77,77,5.48,359450,2.7,218.09,3.23,206.97,-3.17,3.3,-130.99,22.08,-3.95
1,2026-09-03,Rolling 3 Months,2025-08-01,2025-10-31,14216,Zip,33511,"Tampa, FL metro area",155,17.42,390000,1.3,36,5,98.34,0.07,13.55,-1.6,184,-2.13,359,9.45,176,12.82,173,11.61,399000,6.4,217.64,-1.49,217.86,-0.21,3.5,-14.21,31.79,2.76
2,2026-09-03,Rolling 3 Months,2025-08-01,2025-10-31,14220,Zip,33523,"Tampa, FL metro area",37,-27.45,299000,8.73,89,59,96.09,-0.15,10.81,2.97,68,21.43,136,18.26,78,36.84,57,16.33,308595,3.31,188.87,3.85,163.88,-12.41,6.5,303.74,17.54,-8.99
3,2026-09-03,Rolling 3 Months,2025-08-01,2025-10-31,14222,Zip,33525,"Tampa, FL metro area",96,-13.51,349550,-1.47,66,-6,97.97,-0.54,5.21,-2.9,113,1.8,261,-1.14,148,0.68,97,-17.8,389100,-0.23,194.37,-1.51,188.07,-3.45,4.7,66.65,12.37,-0.34
4,2026-09-03,Rolling 3 Months,2025-08-01,2025-10-31,14224,Zip,33527,"Tampa, FL metro area",19,-29.63,455000,0,57,23,96.3,0.19,5.26,-16.96,25,-16.67,59,-7.81,35,9.38,24,-25,565000,5.62,226.23,-3.6,220.59,1.63,5.6,201.46,20.83,-1.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111401,2026-09-03,Rolling 3 Months,2016-08-01,2016-10-31,13685,Zip,32628,NA,1,0,86900,247.6,127,NA,99.31,10.03,0,0,5,0,13,116.67,11,83.33,1,0,79900,8.71,50.76,4.14,39.39,227.12,33.7,1533.33,0,0
111402,2026-09-03,Rolling 3 Months,2016-08-01,2016-10-31,13695,Zip,32648,NA,4,33.33,51850,-70.54,247,69,71.36,-14.17,0,0,3,NA,15,114.29,12,140,4,33.33,159900,NA,140.83,NA,67.15,-64.44,9.2,408.89,0,0
111403,2026-09-03,Rolling 3 Months,2016-08-01,2016-10-31,13708,Zip,32680,NA,18,63.64,62000,-53.73,95,-144,85.97,-5.77,5.56,-12.63,16,-5.88,50,8.7,30,-21.05,18,80,119300,-14.79,77.27,-19.48,65.13,-40.64,5.1,-548.28,0,0
111404,2026-09-03,Rolling 3 Months,2016-08-01,2016-10-31,14193,Zip,33471,NA,8,33.33,67750,17.72,171,24,88.48,4.81,0,0,12,33.33,30,-9.09,22,-8.33,10,25,144450,11.2,77.36,-11.95,42.32,-16.92,8.4,-383.33,0,0
111405,2026-09-03,Rolling 3 Months,2016-08-01,2016-10-31,14763,Zip,34974,NA,75,-1.32,84500,16.15,110,12,92.56,1.08,12,5.42,84,-5.62,218,1.4,146,5.8,72,-2.7,105900,1.34,78.13,-2.78,66.9,-1.46,6,40.14,0,-1.35

We have filtered down to some key dataframes

HISTORICAL DATA
- `fl_historical`
- `central_fl_historical`
- `orl_historical`

AUGUST 2026 DATA
- `fl_august`
- `central_fl_august`
- `orl_august`


`Alcime`: data for the zips Jeanine Serves

`redfin`: redfin data with more standardized metrics

# Core metrics: seller-favored, balanced, or buyer-favored

## How the two sources work together

| | Redfin | Realtor.com |
|---|---|---|
| Based on | Closed sales | Active listings |
| Timing | Lagging: reflects deals already done | Leading: changes before sales do |
| Period | Rolling 3-month windows | Single months |
| Benchmarks | Industry standards apply | No standard benchmarks |
| Role | Sets the label | Confirms the label, signals direction |

Each zip gets three outputs:
1. **Label:** Seller-favored / Balanced / Buyer-favored (Redfin benchmarks)
2. **Confidence:** High / Mixed (do both sources agree?)
3. **Outlook:** Heating up / Steady / Cooling (leading signals)

## Joining the data

- Key: zip (as string) + Redfin period end date.
- Realtor.com monthly values are averaged over the same 3 months as each
  Redfin window (e.g. Redfin "Aug 2026" = average of Realtor.com Jun, Jul,
  Aug 2026).
- Check after joining: row count, and every one of Jeanine's zips present in
  both sources for each comparison window.

## Dimension 1: Supply

**Primary (Redfin):** `MONTHS OF SUPPLY`
Check: ≈ INVENTORY ÷ (HOMES SOLD ÷ 3). Use INVENTORY, not ACTIVE LISTINGS.

- Seller-favored: under 4 months
- Balanced: 4–6 months
- Buyer-favored: over 6 months
(Benchmark source: [cite]. Redfin's reporting uses 4–5 months as balanced.)

**Supporting (Realtor.com):** `pending_ratio` (pending ÷ active listings)
Should move opposite to months of supply.

**Leading (both):**
- Supply flow: Redfin `NEW LISTINGS ÷ HOMES SOLD`. Above 1 = inventory
  building.
- Realtor.com `new_listing_count` vs. same month last year: a monthly early
  read on new supply.

## Dimension 2: Speed

**Primary (Redfin):** `MEDIAN DAYS ON MARKET` (sold homes)

- Seller-favored: under 30 days
- Balanced: 30–60 days
- Buyer-favored: over 60 days

**Supporting:**
- Redfin `PERCENT OFF MARKET IN TWO WEEKS`: higher = hotter demand.
- Realtor.com `median_days_on_market` (listings): should move in the same
  direction as Redfin's.

**Leading:** Redfin `PENDING SALES` vs. a year earlier. Pending sales lead
closed sales by 1–2 months.

## Dimension 3: Price leverage

**Primary (Redfin):** `AVERAGE SALE TO LIST RATIO`

- Seller-favored: 99% or higher
- Balanced: 95% to under 99%
- Buyer-favored: under 95%
(Balanced-band cutoff is my choice; see decision log.)

**Supporting:** Redfin `SHARE SOLD ABOVE ORIGINAL LIST`. The client-friendly
version ("X% of homes here sold over asking").

**Leading (Realtor.com):** `price_reduced_share`. Sellers cut prices before
they sell, so rising price cuts usually show up before sale-to-list falls.
This is the strongest early-warning signal across both sources.

**Note:** Redfin's sale-to-list compares the sale price to the *final* list
price, after any cuts. A zip can show 98% sale-to-list while 40% of
listings had to cut first. The two together give the full picture:
how often sellers came down (Realtor.com) and how far below the final
price they closed (Redfin).

## Dimension 4: Price trend

- Redfin `MEDIAN SALE PRICE PER SQ.FT.` vs. a year earlier: what buyers
  actually paid.
- Realtor.com `median_listing_price_per_square_foot` vs. a year earlier:
  what sellers are asking.
- Per square foot is used instead of median price, which is distorted when
  the mix of homes changes.
- If asking prices rise while sale prices are flat, sellers are
  overpricing for the market. Useful for listing appointments.

## Turning metrics into outputs

**1. Label (the map)**
Each primary metric (months of supply, days on market, sale-to-list) votes
using its benchmarks. Label = majority vote. If all three disagree,
months of supply decides.

**2. Confidence**
For each dimension, check whether the Realtor.com supporting signal agrees
with the Redfin primary metric (same direction vs. the same window last
year).
- High: all three primary metrics agree, and Realtor.com agrees on at
  least 2 of 3 dimensions.
- Mixed: anything else.

**3. Outlook**
Based on leading signals vs. the same window last year:
- Cooling: price reduced share rising, pending sales falling, supply flow
  above 1. (2 of 3 = Cooling)
- Heating up: the reverse. (2 of 3 = Heating up)
- Steady: otherwise.

Displayed together, e.g.: "Balanced (High confidence), Cooling."

**4. Change since 2022 and 2019 (the bar chart)**
- Headline: change in months of supply, Aug 2022 window → Aug 2026 window.
- Also shown: change in label (e.g. Seller-favored → Balanced).
- 2022 = peak market (distance from the frenzy).
- 2019 = normal market (has the zip normalized or overcorrected?).
- History by source: Realtor.com monthly data and the Redfin Key Metrics
  file cover 2016 onward. If the All Metrics file only starts in 2023,
  2022 months of supply and sale-to-list are reconstructed from the YoY
  columns (approximate); 2019 comparisons use days on market, pending
  sales, new listings, and price reduced share.

## Limitations

- Redfin periods are rolling 3-month windows; labels react to change more
  slowly than single months.
- Redfin sale-to-list measures against the final list price, not the
  original; price cuts before sale are captured separately.
- Low-volume zips are excluded or flagged (see decision log for cutoff).
  Redfin suppresses some values in small zips.
- Reconstructed 2022 values are approximate.
- All property types are combined; condo-heavy zips like 32801 are compared
  against single-family-heavy zips. Property-type split is v2.
- Zips don't match neighborhoods exactly.
- Benchmarks are industry rules of thumb; cutoffs and sources are in the
  decision log.

# Data Profiling

now we enter the cleaning -> eda -> further cleaning process

In [ ]:
orl_historical.reset_index(inplace=True, drop=True)
#one row = one zip code within the greater orlando area's monthly data 0 median price, pending listings, tital listings, etc
# why are some like median_listing_price_yy or median_listing_price_mm tiny decimals?

## Explore the different columns, shape, and rows

In [31]:
orl_historical.info() # is the august data folded in to the historical data? 
orl_historical.shape
orl_historical.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 2440 entries, 7162 to 3451835
Data columns (total 48 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   month_date_yyyymm                        2440 non-null   int64
 1   postal_code                              2440 non-null   int64
 2   zip_name                                 2440 non-null   object
 3   median_listing_price                     2440 non-null   float64
 4   median_listing_price_mm                  2200 non-null   float64
 5   median_listing_price_yy                  2200 non-null   float64
 6   active_listing_count                     2440 non-null   int64
 7   active_listing_count_mm                  2200 non-null   float64
 8   active_listing_count_yy                  2200 non-null   float64
 9   median_days_on_market                    2440 non-null   float64
 10  median_days_on_market_mm                 2200 non-null   float64
 11  median_days_on_market_yy                 2200 non-null   float64
 12  new_listing_count                        2440 non-null   int64
 13  new_listing_count_mm                     2200 non-null   float64
 14  new_listing_count_yy                     2200 non-null   float64
 15  price_increased_count                    2440 non-null   int64
 16  price_increased_count_mm                 1195 non-null   float64
 17  price_increased_count_yy                 1300 non-null   float64
 18  price_increased_share                    2440 non-null   float64
 19  price_increased_share_mm                 2200 non-null   float64
 20  price_increased_share_yy                 2200 non-null   float64
 21  price_reduced_count                      2440 non-null   float64
 22  price_reduced_count_mm                   2184 non-null   float64
 23  price_reduced_count_yy                   2184 non-null   float64
 24  price_reduced_share                      2440 non-null   float64
 25  price_reduced_share_mm                   2200 non-null   float64
 26  price_reduced_share_yy                   2200 non-null   float64
 27  pending_listing_count                    2440 non-null   float64
 28  pending_listing_count_mm                 2200 non-null   float64
 29  pending_listing_count_yy                 2200 non-null   float64
 30  median_listing_price_per_square_foot     2440 non-null   float64
 31  median_listing_price_per_square_foot_mm  2200 non-null   float64
 32  median_listing_price_per_square_foot_yy  2200 non-null   float64
 33  median_square_feet                       2440 non-null   float64
 34  median_square_feet_mm                    2200 non-null   float64
 35  median_square_feet_yy                    2200 non-null   float64
 36  average_listing_price                    2440 non-null   float64
 37  average_listing_price_mm                 2200 non-null   float64
 38  average_listing_price_yy                 2200 non-null   float64
 39  total_listing_count                      2440 non-null   int64
 40  total_listing_count_mm                   2200 non-null   float64
 41  total_listing_count_yy                   2200 non-null   float64
 42  pending_ratio                            2440 non-null   float64
 43  pending_ratio_mm                         2200 non-null   float64
 44  pending_ratio_yy                         2200 non-null   float64
 45  quality_flag                             2200 non-null   float64
 46  city                                     2440 non-null   object
 47  state                                    2440 non-null   object
dtypes: float64(39), int64(6), object(3)
memory usage: 934.1+ KB

,month_date_yyyymm,postal_code,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,median_days_on_market_mm,median_days_on_market_yy,new_listing_count,new_listing_count_mm,new_listing_count_yy,price_increased_count,price_increased_count_mm,price_increased_count_yy,price_increased_share,price_increased_share_mm,price_increased_share_yy,price_reduced_count,price_reduced_count_mm,price_reduced_count_yy,price_reduced_share,price_reduced_share_mm,price_reduced_share_yy,pending_listing_count,pending_listing_count_mm,pending_listing_count_yy,median_listing_price_per_square_foot,median_listing_price_per_square_foot_mm,median_listing_price_per_square_foot_yy,median_square_feet,median_square_feet_mm,median_square_feet_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag
count,2440.000000,2440.0000,2.440000e+03,2200.000000,2200.000000,2440.000000,2200.000000,2200.000000,2440.000000,2200.000000,2200.000000,2440.000000,2200.000000,2200.000000,2440.000000,1195.000000,1300.000000,2440.000000,2200.000000,2200.00000,2440.000000,2184.000000,2184.000000,2440.000000,2200.000000,2200.000000,2440.000000,2200.000000,2200.000000,2440.000000,2200.000000,2200.000000,2440.000000,2200.000000,2200.000000,2.440000e+03,2200.000000,2200.000000,2440.000000,2200.000000,2200.000000,2440.000000,2200.000000,2200.000000,2200.000000
mean,202114.713115,33098.8500,4.090252e+05,0.004972,0.063680,119.898770,0.011006,0.131668,54.690164,0.020831,0.076093,57.989344,0.048296,0.028811,4.717213,-0.065128,-0.152064,0.015463,-0.000435,-0.00278,49.266393,0.070346,0.284332,0.186239,-0.000196,0.001779,78.057787,0.007587,-0.020900,212.974590,0.005320,0.072521,1941.552459,-0.000260,-0.009682,5.239252e+05,0.005141,0.063295,197.832787,0.002963,0.022802,0.876738,-0.004957,-0.045738,0.201364
std,295.645630,706.3388,1.883416e+05,0.051335,0.136002,97.945011,0.140342,0.592962,16.925830,0.190799,0.363049,37.660117,0.348270,0.345492,8.186351,1.046062,1.131470,0.020547,0.017712,0.02324,41.289321,0.491341,1.287337,0.079270,0.057778,0.083678,54.891749,0.164156,0.274241,65.365113,0.025177,0.098346,600.478253,0.048561,0.094263,3.466270e+05,0.052981,0.151993,140.240451,0.086164,0.281966,0.662955,0.269599,0.688369,0.401110
min,201607.000000,32703.0000,8.532500e+04,-0.373700,-0.430800,8.000000,-0.500000,-0.813700,11.000000,-0.596800,-0.725500,6.000000,-0.733300,-0.785700,0.000000,-1.000000,-1.000000,0.000000,-0.085000,-0.11760,0.000000,-1.000000,-1.000000,0.000000,-0.261900,-0.297000,11.000000,-0.521300,-0.722400,73.000000,-0.093700,-0.147000,1015.000000,-0.302300,-0.397400,1.021040e+05,-0.352900,-0.639200,23.000000,-0.281100,-0.576600,0.101300,-2.258800,-3.262800,0.000000
25%,201901.000000,32804.7500,2.887438e+05,-0.018300,-0.022075,52.000000,-0.065200,-0.200000,42.000000,-0.095350,-0.148775,34.000000,-0.174175,-0.200000,0.000000,-1.000000,-1.000000,0.000000,-0.007500,-0.01300,22.000000,-0.200000,-0.333300,0.132350,-0.036100,-0.055100,41.000000,-0.098450,-0.188150,156.000000,-0.008500,0.004900,1398.000000,-0.023900,-0.064425,3.187818e+05,-0.020625,-0.030825,107.000000,-0.049325,-0.152500,0.445150,-0.084150,-0.270025,0.000000
50%,202107.500000,32813.5000,3.722830e+05,0.000100,0.044800,99.000000,0.000000,0.016750,53.000000,0.025450,0.031950,50.000000,0.000000,0.000000,2.000000,-0.333300,-0.500000,0.008900,0.000000,0.00000,40.000000,0.000000,-0.020000,0.187900,0.001000,-0.002950,64.000000,-0.014800,-0.055900,213.500000,0.003000,0.051550,1843.000000,-0.000300,-0.010350,4.431020e+05,0.002550,0.036750,171.000000,-0.001900,-0.007750,0.666250,-0.001050,-0.039050,0.000000
75%,202402.000000,32829.0000,4.895500e+05,0.024800,0.131750,148.000000,0.067075,0.341200,66.000000,0.123300,0.240700,70.000000,0.187500,0.189525,6.000000,0.333300,0.000000,0.023225,0.006700,0.00720,64.000000,0.228175,0.461500,0.240850,0.034725,0.057800,99.000000,0.095350,0.110125,254.000000,0.016825,0.108975,2278.000000,0.020525,0.043750,5.978458e+05,0.028100,0.131650,235.000000,0.048700,0.150950,1.078950,0.077575,0.150175,0.000000
max,202608.000000,34787.0000,1.369162e+06,0.457000,0.847600,657.000000,1.734000,6.298200,130.000000,1.240000,3.125000,262.000000,2.500000,2.666700,90.000000,10.000000,9.000000,0.127800,0.101000,0.10480,284.000000,7.000000,17.000000,0.450900,0.309300,0.363300,351.000000,0.818200,1.933300,378.000000,0.169600,0.549500,4042.000000,0.313800,0.555700,2.514529e+06,0.673900,0.858400,1007.000000,0.627100,2.485300,5.532300,2.264700,4.212000,1.000000

In [ ]:
orl_historical.rename(columns={'month_date_yyyymm':'month_year'}, inplace=True)

/var/folders/cm/46nnvpl978b_vb10b1dp7rp80000gn/T/ipykernel_21615/1807519895.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orl_historical.rename(columns={'month_date_yyyymm':'month_year'}, inplace=True)

In [ ]:
# lets create a function that spits out month_year as 2 columns: month and year 
def split_monthYear(month_year):
    ''' create a function that spits out month_year as 2 columns: month and year ''' 
    string_monthYear = month_year.astype(str)
    year = string_monthYear.str[:4].astype(int)
    month = string_monthYear.str[4:].astype(int)
    return pd.DataFrame({'year': year, 'month': month})

orl_historical[['year', 'month']] = split_monthYear(orl_historical['month_year'])
orl_historical

/var/folders/cm/46nnvpl978b_vb10b1dp7rp80000gn/T/ipykernel_21615/1295504457.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orl_historical[['year', 'month']] = split_monthYear(orl_historical['month_year'])
/var/folders/cm/46nnvpl978b_vb10b1dp7rp80000gn/T/ipykernel_21615/1295504457.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orl_historical[['year', 'month']] = split_monthYear(orl_historical['month_year'])

,month_year,postal_code,zip_name,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,median_days_on_market_mm,median_days_on_market_yy,new_listing_count,new_listing_count_mm,new_listing_count_yy,price_increased_count,price_increased_count_mm,price_increased_count_yy,price_increased_share,price_increased_share_mm,price_increased_share_yy,price_reduced_count,price_reduced_count_mm,price_reduced_count_yy,price_reduced_share,price_reduced_share_mm,price_reduced_share_yy,pending_listing_count,pending_listing_count_mm,pending_listing_count_yy,median_listing_price_per_square_foot,median_listing_price_per_square_foot_mm,median_listing_price_per_square_foot_yy,median_square_feet,median_square_feet_mm,median_square_feet_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag,city,state,year,month
0,202608,32828,"orlando, fl",489450.0,-0.0056,0.0136,187,0.0418,0.2897,65.0,0.1017,0.1504,60,-0.2500,0.2500,0,-1.0000,NaN,0.0000,-0.0116,0.0000,100.0,0.3158,0.3158,0.3003,0.0681,-0.0217,62.0,-0.1448,0.3778,224.0,0.0033,-0.0366,2083.0,-0.0305,0.0462,474980.0,-0.0103,-0.0550,252,0.0000,0.3194,0.3316,-0.0723,0.0212,0.0,orlando,fl,2026,8
1,202608,32712,"apopka, fl",455000.0,-0.0246,-0.0712,259,0.0058,0.0792,72.0,0.0511,0.1901,72,-0.2800,-0.1000,4,-0.3333,-0.5,0.0080,-0.0034,-0.0104,124.0,0.2917,0.2400,0.2650,0.0797,0.0351,154.0,0.0233,0.3162,207.0,-0.0006,-0.0519,2077.0,0.0000,-0.0699,494250.0,-0.0276,-0.0921,411,0.0074,0.1743,0.5946,0.0101,0.1071,0.0,apopka,fl,2026,8
2,202608,34761,"ocoee, fl",438000.0,0.0368,-0.0374,137,0.0186,0.1513,68.0,0.0837,0.1930,44,-0.1200,-0.0833,0,NaN,-1.0,0.0000,0.0000,-0.0161,68.0,0.2593,0.1333,0.2595,0.0620,-0.0071,76.0,0.0000,0.0857,219.0,-0.0029,-0.0401,1915.0,0.0606,-0.0103,465740.0,0.0446,-0.0939,215,0.0190,0.1436,0.5547,-0.0103,-0.0335,0.0,ocoee,fl,2026,8
3,202608,32803,"orlando, fl",570000.0,-0.0150,0.1692,88,-0.0112,-0.1927,54.0,0.0693,-0.1818,40,0.0526,-0.1667,0,NaN,NaN,0.0000,0.0000,0.0000,36.0,-0.0526,-0.1000,0.2543,0.0470,0.0543,36.0,0.1077,-0.1818,362.0,0.0038,0.0593,1839.0,0.0068,0.3007,822287.0,0.0313,0.3269,125,0.0246,-0.1554,0.4091,0.0439,0.0054,0.0,orlando,fl,2026,8
4,202608,32835,"orlando, fl",249950.0,-0.0002,0.0161,218,-0.1138,-0.2829,80.0,0.1080,-0.0756,52,-0.1875,0.1818,4,0.0000,NaN,0.0125,0.0016,0.0125,68.0,-0.1053,-0.1905,0.1960,-0.0206,-0.0268,57.0,0.2258,0.2955,194.0,0.0062,-0.0298,1408.0,0.0000,0.0957,392863.0,-0.0126,0.1963,273,-0.0586,-0.2178,0.2615,0.0724,0.1167,0.0,orlando,fl,2026,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2435,201607,32827,"orlando, fl",509560.0,NaN,NaN,135,NaN,NaN,72.0,NaN,NaN,30,NaN,NaN,6,NaN,NaN,0.0290,NaN,NaN,26.0,NaN,NaN,0.1164,NaN,NaN,46.0,NaN,NaN,187.0,NaN,NaN,2853.0,NaN,NaN,827654.0,NaN,NaN,182,NaN,NaN,0.3407,NaN,NaN,NaN,orlando,fl,2016,7
2436,201607,32826,"orlando, fl",250975.0,NaN,NaN,42,NaN,NaN,35.0,NaN,NaN,42,NaN,NaN,0,NaN,NaN,0.0000,NaN,NaN,16.0,NaN,NaN,0.1432,NaN,NaN,47.0,NaN,NaN,122.0,NaN,NaN,2179.0,NaN,NaN,266435.0,NaN,NaN,88,NaN,NaN,1.1205,NaN,NaN,NaN,orlando,fl,2016,7
2437,201607,32806,"orlando, fl",323675.0,NaN,NaN,127,NaN,NaN,44.0,NaN,NaN,76,NaN,NaN,4,NaN,NaN,0.0136,NaN,NaN,60.0,NaN,NaN,0.2179,NaN,NaN,93.0,NaN,NaN,172.0,NaN,NaN,1918.0,NaN,NaN,412155.0,NaN,NaN,219,NaN,NaN,0.7312,NaN,NaN,NaN,orlando,fl,2016,7
2438,201607,32828,"orlando, fl",282350.0,NaN,NaN,198,NaN,NaN,42.0,NaN,NaN,134,NaN,NaN,4,NaN,NaN,0.0075,NaN,NaN,114.0,NaN,NaN,0.2094,NaN,NaN,187.0,NaN,NaN,122.0,NaN,NaN,2380.0,NaN,NaN,298888.0,NaN,NaN,385,NaN,NaN,0.9444,NaN,NaN,NaN,orlando,fl,2016,7
2439,201607,32810,"orlando, fl",147000.0,NaN,NaN,88,NaN,NaN,31.0,NaN,NaN,64,NaN,NaN,6,NaN,NaN,0.0263,NaN,NaN,40.0,NaN,NaN,0.1542,NaN,NaN,90.0,NaN,NaN,100.0,NaN,NaN,1350.0,NaN,NaN,151563.0,NaN,NaN,177,NaN,NaN,1.0286,NaN,NaN,NaN,orlando,fl,2016,7

In [ ]:
orl_historical.duplicated().sum() # no duplicate rows!

np.int64(0)

In [28]:
redfin.shape
redfin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111406 entries, 0 to 111405
Data columns (total 36 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   LAST UPDATED                                 111406 non-null  datetime64[us]
 1   FREQUENCY                                    111406 non-null  object
 2   PERIOD BEGIN                                 111406 non-null  datetime64[us]
 3   PERIOD END                                   111406 non-null  datetime64[us]
 4   REGION ID                                    111406 non-null  int64
 5   REGION TYPE                                  111406 non-null  object
 6   REGION NAME                                  111406 non-null  object
 7   METRO                                        111406 non-null  object
 8   HOMES SOLD                                   111406 non-null  object
 9   HOMES SOLD YOY (%)                           111406 non-null  object
 10  MEDIAN SALE PRICE NSA ($)                    111406 non-null  object
 11  MEDIAN SALE PRICE NSA YOY (%)                111406 non-null  object
 12  MEDIAN DAYS ON MARKET (DAYS)                 111406 non-null  object
 13  MEDIAN DAYS ON MARKET YOY (DAYS)             111406 non-null  object
 14  AVERAGE SALE TO LIST RATIO (%)               111406 non-null  object
 15  AVERAGE SALE TO LIST RATIO YOY (PPTS)        111406 non-null  object
 16  SHARE SOLD ABOVE ORIGINAL LIST (%)           111406 non-null  object
 17  SHARE SOLD ABOVE ORIGINAL LIST YOY (PPTS)    111406 non-null  object
 18  NEW LISTINGS                                 111406 non-null  object
 19  NEW LISTINGS YOY (%)                         111406 non-null  object
 20  ACTIVE LISTINGS                              111406 non-null  object
 21  ACTIVE LISTINGS YOY (%)                      111406 non-null  object
 22  INVENTORY                                    111406 non-null  object
 23  INVENTORY YOY (%)                            111406 non-null  object
 24  PENDING SALES                                111406 non-null  object
 25  PENDING SALES YOY (%)                        111406 non-null  object
 26  MEDIAN NEW LISTING PRICE ($)                 111406 non-null  object
 27  MEDIAN NEW LISTING PRICE YOY (%)             111406 non-null  object
 28  MEDIAN NEW LISTING PRICE PER SQ.FT. ($)      111406 non-null  object
 29  MEDIAN NEW LISTING PRICE PER SQ.FT. YOY (%)  111406 non-null  object
 30  MEDIAN SALE PRICE PER SQ.FT. ($)             111406 non-null  object
 31  MEDIAN SALE PRICE PER SQ.FT. YOY (%)         111406 non-null  object
 32  MONTHS OF SUPPLY                             111406 non-null  object
 33  MONTHS OF SUPPLY YOY (%)                     111406 non-null  object
 34  PERCENT OFF MARKET IN TWO WEEKS (%)          111406 non-null  object
 35  PERCENT OFF MARKET IN TWO WEEKS YOY (PPTS)   111406 non-null  object
dtypes: datetime64[us](3), int64(1), object(32)
memory usage: 30.6+ MB

In [ ]:
redfin.isna().sum().sum() # this is becuase it uses NA instead of null ? but shouldnt it still be counted as null?
(redfin == 'NA').sum().sort_values()  # ohhh, its bc theyre strings
# convert NA to null

LAST UPDATED                                      0
FREQUENCY                                         0
PERIOD BEGIN                                      0
PERIOD END                                        0
REGION ID                                         0
REGION TYPE                                       0
REGION NAME                                       0
ACTIVE LISTINGS                                 228
INVENTORY                                       951
ACTIVE LISTINGS YOY (%)                         962
NEW LISTINGS                                   1457
MEDIAN NEW LISTING PRICE ($)                   1462
MEDIAN NEW LISTING PRICE PER SQ.FT. ($)        1536
PENDING SALES                                  1647
PERCENT OFF MARKET IN TWO WEEKS (%)            1647
SHARE SOLD ABOVE ORIGINAL LIST (%)             1868
MEDIAN SALE PRICE NSA ($)                      1868
HOMES SOLD                                     1868
INVENTORY YOY (%)                              1872
AVERAGE SALE TO LIST RATIO (%)                 1877
MEDIAN SALE PRICE PER SQ.FT. ($)               1920
MEDIAN DAYS ON MARKET (DAYS)                   2115
MONTHS OF SUPPLY                               2559
NEW LISTINGS YOY (%)                           2599
MEDIAN NEW LISTING PRICE YOY (%)               2602
MEDIAN NEW LISTING PRICE PER SQ.FT. YOY (%)    2694
PERCENT OFF MARKET IN TWO WEEKS YOY (PPTS)     2827
PENDING SALES YOY (%)                          2827
MEDIAN SALE PRICE NSA YOY (%)                  3051
HOMES SOLD YOY (%)                             3051
SHARE SOLD ABOVE ORIGINAL LIST YOY (PPTS)      3051
AVERAGE SALE TO LIST RATIO YOY (PPTS)          3062
MEDIAN SALE PRICE PER SQ.FT. YOY (%)           3112
MEDIAN DAYS ON MARKET YOY (DAYS)               3445
MONTHS OF SUPPLY YOY (%)                       3661
METRO                                          6730
dtype: int64

Renamed the monthyear column of realtor.com data, split it into month and year

## Explore the Nulls
- Drop/Fill, and do a little eda (summary statistics and visualizations to spot patterns, trends, and hidden anomalies)

In [ ]:
orl_historical

,month_year,postal_code,zip_name,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,median_days_on_market_mm,median_days_on_market_yy,new_listing_count,new_listing_count_mm,new_listing_count_yy,price_increased_count,price_increased_count_mm,price_increased_count_yy,price_increased_share,price_increased_share_mm,price_increased_share_yy,price_reduced_count,price_reduced_count_mm,price_reduced_count_yy,price_reduced_share,price_reduced_share_mm,price_reduced_share_yy,pending_listing_count,pending_listing_count_mm,pending_listing_count_yy,median_listing_price_per_square_foot,median_listing_price_per_square_foot_mm,median_listing_price_per_square_foot_yy,median_square_feet,median_square_feet_mm,median_square_feet_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag,city,state,year,month
0,202608,32828,"orlando, fl",489450.0,-0.0056,0.0136,187,0.0418,0.2897,65.0,0.1017,0.1504,60,-0.2500,0.2500,0,-1.0000,NaN,0.0000,-0.0116,0.0000,100.0,0.3158,0.3158,0.3003,0.0681,-0.0217,62.0,-0.1448,0.3778,224.0,0.0033,-0.0366,2083.0,-0.0305,0.0462,474980.0,-0.0103,-0.0550,252,0.0000,0.3194,0.3316,-0.0723,0.0212,0.0,orlando,fl,2026,8
1,202608,32712,"apopka, fl",455000.0,-0.0246,-0.0712,259,0.0058,0.0792,72.0,0.0511,0.1901,72,-0.2800,-0.1000,4,-0.3333,-0.5,0.0080,-0.0034,-0.0104,124.0,0.2917,0.2400,0.2650,0.0797,0.0351,154.0,0.0233,0.3162,207.0,-0.0006,-0.0519,2077.0,0.0000,-0.0699,494250.0,-0.0276,-0.0921,411,0.0074,0.1743,0.5946,0.0101,0.1071,0.0,apopka,fl,2026,8
2,202608,34761,"ocoee, fl",438000.0,0.0368,-0.0374,137,0.0186,0.1513,68.0,0.0837,0.1930,44,-0.1200,-0.0833,0,NaN,-1.0,0.0000,0.0000,-0.0161,68.0,0.2593,0.1333,0.2595,0.0620,-0.0071,76.0,0.0000,0.0857,219.0,-0.0029,-0.0401,1915.0,0.0606,-0.0103,465740.0,0.0446,-0.0939,215,0.0190,0.1436,0.5547,-0.0103,-0.0335,0.0,ocoee,fl,2026,8
3,202608,32803,"orlando, fl",570000.0,-0.0150,0.1692,88,-0.0112,-0.1927,54.0,0.0693,-0.1818,40,0.0526,-0.1667,0,NaN,NaN,0.0000,0.0000,0.0000,36.0,-0.0526,-0.1000,0.2543,0.0470,0.0543,36.0,0.1077,-0.1818,362.0,0.0038,0.0593,1839.0,0.0068,0.3007,822287.0,0.0313,0.3269,125,0.0246,-0.1554,0.4091,0.0439,0.0054,0.0,orlando,fl,2026,8
4,202608,32835,"orlando, fl",249950.0,-0.0002,0.0161,218,-0.1138,-0.2829,80.0,0.1080,-0.0756,52,-0.1875,0.1818,4,0.0000,NaN,0.0125,0.0016,0.0125,68.0,-0.1053,-0.1905,0.1960,-0.0206,-0.0268,57.0,0.2258,0.2955,194.0,0.0062,-0.0298,1408.0,0.0000,0.0957,392863.0,-0.0126,0.1963,273,-0.0586,-0.2178,0.2615,0.0724,0.1167,0.0,orlando,fl,2026,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2435,201607,32827,"orlando, fl",509560.0,NaN,NaN,135,NaN,NaN,72.0,NaN,NaN,30,NaN,NaN,6,NaN,NaN,0.0290,NaN,NaN,26.0,NaN,NaN,0.1164,NaN,NaN,46.0,NaN,NaN,187.0,NaN,NaN,2853.0,NaN,NaN,827654.0,NaN,NaN,182,NaN,NaN,0.3407,NaN,NaN,NaN,orlando,fl,2016,7
2436,201607,32826,"orlando, fl",250975.0,NaN,NaN,42,NaN,NaN,35.0,NaN,NaN,42,NaN,NaN,0,NaN,NaN,0.0000,NaN,NaN,16.0,NaN,NaN,0.1432,NaN,NaN,47.0,NaN,NaN,122.0,NaN,NaN,2179.0,NaN,NaN,266435.0,NaN,NaN,88,NaN,NaN,1.1205,NaN,NaN,NaN,orlando,fl,2016,7
2437,201607,32806,"orlando, fl",323675.0,NaN,NaN,127,NaN,NaN,44.0,NaN,NaN,76,NaN,NaN,4,NaN,NaN,0.0136,NaN,NaN,60.0,NaN,NaN,0.2179,NaN,NaN,93.0,NaN,NaN,172.0,NaN,NaN,1918.0,NaN,NaN,412155.0,NaN,NaN,219,NaN,NaN,0.7312,NaN,NaN,NaN,orlando,fl,2016,7
2438,201607,32828,"orlando, fl",282350.0,NaN,NaN,198,NaN,NaN,42.0,NaN,NaN,134,NaN,NaN,4,NaN,NaN,0.0075,NaN,NaN,114.0,NaN,NaN,0.2094,NaN,NaN,187.0,NaN,NaN,122.0,NaN,NaN,2380.0,NaN,NaN,298888.0,NaN,NaN,385,NaN,NaN,0.9444,NaN,NaN,NaN,orlando,fl,2016,7
2439,201607,32810,"orlando, fl",147000.0,NaN,NaN,88,NaN,NaN,31.0,NaN,NaN,64,NaN,NaN,6,NaN,NaN,0.0263,NaN,NaN,40.0,NaN,NaN,0.1542,NaN,NaN,90.0,NaN,NaN,100.0,NaN,NaN,1350.0,NaN,NaN,151563.0,NaN,NaN,177,NaN,NaN,1.0286,NaN,NaN,NaN,orlando,fl,2016,7

In [ ]:
orl_historical.isna().sum() #240 to 256ish, some at 1140+ - total of 8897

month_year                                    0
postal_code                                   0
zip_name                                      0
median_listing_price                          0
median_listing_price_mm                     240
median_listing_price_yy                     240
active_listing_count                          0
active_listing_count_mm                     240
active_listing_count_yy                     240
median_days_on_market                         0
median_days_on_market_mm                    240
median_days_on_market_yy                    240
new_listing_count                             0
new_listing_count_mm                        240
new_listing_count_yy                        240
price_increased_count                         0
price_increased_count_mm                   1245
price_increased_count_yy                   1140
price_increased_share                         0
price_increased_share_mm                    240
price_increased_share_yy                    240
price_reduced_count                           0
price_reduced_count_mm                      256
price_reduced_count_yy                      256
price_reduced_share                           0
price_reduced_share_mm                      240
price_reduced_share_yy                      240
pending_listing_count                         0
pending_listing_count_mm                    240
pending_listing_count_yy                    240
median_listing_price_per_square_foot          0
median_listing_price_per_square_foot_mm     240
median_listing_price_per_square_foot_yy     240
median_square_feet                            0
median_square_feet_mm                       240
median_square_feet_yy                       240
average_listing_price                         0
average_listing_price_mm                    240
average_listing_price_yy                    240
total_listing_count                           0
total_listing_count_mm                      240
total_listing_count_yy                      240
pending_ratio                                 0
pending_ratio_mm                            240
pending_ratio_yy                            240
quality_flag                                240
city                                          0
state                                         0
year                                          0
month                                         0
dtype: int64

In [ ]:
orl_historical.isna().mean()
# Months of Inventory: `Active Listings / Monthly Sales = Months of Inventory`
# no null monthly total listings or active listinsg!

month_year                                 0.000000
postal_code                                0.000000
zip_name                                   0.000000
median_listing_price                       0.000000
median_listing_price_mm                    0.098361
median_listing_price_yy                    0.098361
active_listing_count                       0.000000
active_listing_count_mm                    0.098361
active_listing_count_yy                    0.098361
median_days_on_market                      0.000000
median_days_on_market_mm                   0.098361
median_days_on_market_yy                   0.098361
new_listing_count                          0.000000
new_listing_count_mm                       0.098361
new_listing_count_yy                       0.098361
price_increased_count                      0.000000
price_increased_count_mm                   0.510246
price_increased_count_yy                   0.467213
price_increased_share                      0.000000
price_increased_share_mm                   0.098361
price_increased_share_yy                   0.098361
price_reduced_count                        0.000000
price_reduced_count_mm                     0.104918
price_reduced_count_yy                     0.104918
price_reduced_share                        0.000000
price_reduced_share_mm                     0.098361
price_reduced_share_yy                     0.098361
pending_listing_count                      0.000000
pending_listing_count_mm                   0.098361
pending_listing_count_yy                   0.098361
median_listing_price_per_square_foot       0.000000
median_listing_price_per_square_foot_mm    0.098361
median_listing_price_per_square_foot_yy    0.098361
median_square_feet                         0.000000
median_square_feet_mm                      0.098361
median_square_feet_yy                      0.098361
average_listing_price                      0.000000
average_listing_price_mm                   0.098361
average_listing_price_yy                   0.098361
total_listing_count                        0.000000
total_listing_count_mm                     0.098361
total_listing_count_yy                     0.098361
pending_ratio                              0.000000
pending_ratio_mm                           0.098361
pending_ratio_yy                           0.098361
quality_flag                               0.098361
city                                       0.000000
state                                      0.000000
year                                       0.000000
month                                      0.000000
dtype: float64