# Business Goal/Outcome

## Goal
Give a realtor like Jeanine a data-backed answer to the question every seller asks ("What's my home worth, and how long will it take?") and every buyer asks ("Do I have room to negotiate?"), specific to the zip they're standing in.

## Outcomes
- Realtor can price the seller correctly in listing appts 
- Aide buyer consolutations and negotiation strategy
- Help with prospecting and knowing which zips to farm
- Data to feed market update content
- Help relay market expertise

# Research Question
Where in Orlando have sellers lost leverage since 2023, and where do they still have it?

# Hypothesis

**H1: New construction hurt resale sellers most.**  
		In 34787 and 32712, price cut share and days on market will have risen more than the metro average since 2022, because builders' incentives pull buyers away from resale homes.  
		_Rejected if:_ both zips' increases are at or below the metro average.


**H2: Windermere held up.**  
		In 34786, the leverage score will have dropped less than the metro average since 2022, because scarce lakefront and large-lot homes and less rate-sensitive buyers protect sellers.  
		_Rejected if:_ 34786's drop is at or above the metro average. If that happens, the Horizon West portion of the zip may be dragging it down.


**H3: Affordable zips**
 34761 and 32703 will have lost less leverage than 34787 and 32712, because they have less new-construction competition. _Rejected if:_ their drop is the same as or larger than the growth zips'.

# Bring in Data For Prep

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
historical = pd.read_csv('/Users/medhasubramaniyan/Desktop/GitHub_Repos/orlando-seller-leverage-analysis/data/RDC_Inventory_Core_Metrics_Zip_History.csv')
historical

,month_date_yyyymm,postal_code,zip_name,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,median_days_on_market_mm,median_days_on_market_yy,new_listing_count,new_listing_count_mm,new_listing_count_yy,price_increased_count,price_increased_count_mm,price_increased_count_yy,price_increased_share,price_increased_share_mm,price_increased_share_yy,price_reduced_count,price_reduced_count_mm,price_reduced_count_yy,price_reduced_share,price_reduced_share_mm,price_reduced_share_yy,pending_listing_count,pending_listing_count_mm,pending_listing_count_yy,median_listing_price_per_square_foot,median_listing_price_per_square_foot_mm,median_listing_price_per_square_foot_yy,median_square_feet,median_square_feet_mm,median_square_feet_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag
0,202608,74003,"bartlesville, ok",150000.0,0.0000,0.0714,45,-0.0722,0.0714,70.0,0.2335,0.4000,16,0.1429,0.3333,0,NaN,NaN,0.0000,0.0,0.0000,20.0,0.2500,0.0000,0.2174,0.0591,-0.0725,26.0,0.0000,0.3684,103.0,0.0093,0.0731,1377.0,0.0025,-0.1179,208058.0,-0.0086,0.0436,71,-0.0596,0.1639,0.5778,0.0417,0.1254,0.0
1,202608,61353,"paw paw, il",294450.0,0.0865,0.0711,7,0.2727,0.4000,27.0,-0.2895,-0.7823,4,-0.3333,NaN,0,NaN,NaN,0.0000,0.0,0.0000,0.0,-1.0000,NaN,0.0000,-0.4857,0.0000,2.0,0.5000,-0.5000,138.0,-0.0381,-0.0657,2092.0,0.0241,-0.1285,432643.0,0.2654,0.2023,8,0.3333,0.1429,0.2143,0.0325,-0.3857,1.0
2,202608,35765,"pisgah, al",307950.0,0.0448,0.1322,15,0.0345,0.5000,105.0,-0.0024,1.3864,0,-1.0000,NaN,0,NaN,NaN,0.0000,0.0,0.0000,0.0,NaN,-1.0000,0.0000,0.0000,-0.3200,2.0,1.0000,0.0000,145.0,-0.0329,-0.1275,1948.0,0.0000,0.2074,312969.0,-0.0256,-0.1669,18,0.1613,0.3846,0.1333,0.0644,-0.0667,1.0
3,202608,21664,"secretary, md",349900.0,0.0294,0.0218,2,0.3333,-0.5000,54.0,-0.0270,0.1739,0,NaN,NaN,0,NaN,NaN,0.0000,0.0,0.0000,0.0,NaN,NaN,0.0000,0.0000,0.0000,0.0,-1.0000,-1.0000,191.0,-0.0163,0.1149,1830.0,0.0404,0.4338,349900.0,0.0294,0.1915,2,-0.3333,-0.5000,0.0000,-0.6667,-0.2500,0.0
4,202608,37221,"nashville, tn",519900.0,-0.0295,-0.0877,235,0.0129,0.0930,64.0,0.0802,-0.2000,80,-0.2000,0.0000,0,NaN,-1.0,0.0000,0.0,-0.0097,104.0,0.1818,0.4444,0.2708,0.0687,0.0969,77.0,-0.1979,-0.2300,252.0,-0.0174,-0.0443,2009.0,-0.0025,-0.0995,742763.0,0.0067,0.0582,312,-0.0473,-0.0064,0.3277,-0.0861,-0.1375,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3452028,201607,8828,"helmetta, nj",218000.0,NaN,NaN,22,NaN,NaN,67.0,NaN,NaN,4,NaN,NaN,0,NaN,NaN,0.0000,NaN,NaN,2.0,NaN,NaN,0.0769,NaN,NaN,1.0,NaN,NaN,159.0,NaN,NaN,1198.0,NaN,NaN,243027.0,NaN,NaN,22,NaN,NaN,0.0455,NaN,NaN,NaN
3452029,201607,30536,"ellijay, ga",249350.0,NaN,NaN,128,NaN,NaN,86.0,NaN,NaN,26,NaN,NaN,2,NaN,NaN,0.0128,NaN,NaN,34.0,NaN,NaN,0.2257,NaN,NaN,2.0,NaN,NaN,125.0,NaN,NaN,2032.0,NaN,NaN,309281.0,NaN,NaN,128,NaN,NaN,0.0118,NaN,NaN,NaN
3452030,201607,37863,"pigeon forge, tn",224750.0,NaN,NaN,189,NaN,NaN,115.0,NaN,NaN,16,NaN,NaN,0,NaN,NaN,0.0000,NaN,NaN,14.0,NaN,NaN,0.0589,NaN,NaN,39.0,NaN,NaN,150.0,NaN,NaN,1500.0,NaN,NaN,283587.0,NaN,NaN,226,NaN,NaN,0.2042,NaN,NaN,NaN
3452031,201607,32097,"yulee, fl",231973.0,NaN,NaN,150,NaN,NaN,69.0,NaN,NaN,58,NaN,NaN,22,NaN,NaN,0.0606,NaN,NaN,24.0,NaN,NaN,0.0678,NaN,NaN,104.0,NaN,NaN,108.0,NaN,NaN,2094.0,NaN,NaN,324656.0,NaN,NaN,252,NaN,NaN,0.6923,NaN,NaN,NaN
3452032,201607,59064,"pompeys pillar, mt",199500.0,NaN,NaN,1,NaN,NaN,14.0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0.0000,NaN,NaN,0.0,NaN,NaN,0.0000,NaN,NaN,1.0,NaN,NaN,88.0,NaN,NaN,2280.0,NaN,NaN,199500.0,NaN,NaN,1,NaN,NaN,1.0000,NaN,NaN,NaN

In [3]:
august = pd.read_csv('/Users/medhasubramaniyan/Desktop/GitHub_Repos/orlando-seller-leverage-analysis/data/RDC_Inventory_Core_Metrics_Zip.csv')
august

,month_date_yyyymm,postal_code,zip_name,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,median_days_on_market_mm,median_days_on_market_yy,new_listing_count,new_listing_count_mm,new_listing_count_yy,price_increased_count,price_increased_count_mm,price_increased_count_yy,price_increased_share,price_increased_share_mm,price_increased_share_yy,price_reduced_count,price_reduced_count_mm,price_reduced_count_yy,price_reduced_share,price_reduced_share_mm,price_reduced_share_yy,pending_listing_count,pending_listing_count_mm,pending_listing_count_yy,median_listing_price_per_square_foot,median_listing_price_per_square_foot_mm,median_listing_price_per_square_foot_yy,median_square_feet,median_square_feet_mm,median_square_feet_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag
0,202608,78956,"schulenburg, tx",314000.0,-0.1253,0.0502,28,0.1200,0.4000,124.0,-0.0294,1.3396,0,-1.0000,-1.0,0,NaN,NaN,0.0,0.0,0.0,12.0,0.5000,NaN,0.2857,0.0413,0.2857,5.0,0.4286,0.2500,167.0,-0.0139,-0.0169,2113.0,-0.0540,0.0581,410433.0,-0.0986,0.2020,32,0.1228,0.3913,0.1786,0.0386,-0.0214,1
1,202608,30535,"demorest, ga",415000.0,-0.0259,0.0038,55,-0.0090,0.4865,90.0,0.3162,1.0341,20,-0.3333,0.0,0,NaN,NaN,0.0,0.0,0.0,16.0,0.3333,0.3333,0.1633,0.0402,-0.0999,14.0,-0.2632,0.2727,183.0,0.0197,-0.0597,2665.0,0.0744,0.1550,461853.0,-0.0132,0.0613,68,-0.0933,0.4167,0.2545,-0.0878,-0.0428,1
2,202608,83316,"buhl, id",510000.0,0.0000,0.2146,45,-0.0110,-0.0816,79.0,0.0604,-0.0920,12,-0.2500,0.0,0,NaN,NaN,0.0,0.0,0.0,12.0,-0.1429,-0.4000,0.2069,-0.0012,-0.0894,10.0,-0.3548,-0.2857,245.0,-0.0077,0.0134,1970.0,-0.0760,0.0221,699305.0,-0.0023,0.2881,55,-0.0833,-0.1129,0.2222,-0.1184,-0.0635,0
3,202608,94806,"san pablo, ca",577500.0,0.0226,-0.0077,71,0.2034,-0.1013,38.0,-0.1508,-0.0843,36,0.2857,0.0,0,NaN,NaN,0.0,0.0,0.0,24.0,1.0000,0.0000,0.1951,0.0919,0.0432,22.0,-0.2281,-0.3529,387.0,0.0181,-0.1229,1312.0,0.0135,0.0492,574916.0,0.0050,-0.0158,91,0.0581,-0.1947,0.3099,-0.1732,-0.1205,0
4,202608,37820,"new market, tn",735000.0,0.0426,0.4703,23,0.1500,0.0455,57.0,0.0411,-0.1094,4,-0.5000,0.0,0,NaN,NaN,0.0,0.0,0.0,8.0,0.0000,-0.3333,0.1509,-0.1013,-0.1824,7.0,0.0769,-0.3636,262.0,0.0060,0.0535,2714.0,-0.0058,0.2730,771742.0,-0.0668,0.5105,29,0.1154,-0.1714,0.3043,-0.0207,-0.1957,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29046,202608,50546,"havelock, ia",265500.0,0.0000,0.0215,1,0.0000,0.0000,81.0,0.6364,0.0658,0,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,0.0000,0.0000,0.0000,1.0,NaN,0.0000,250.0,0.0000,0.0215,1064.0,0.0000,0.0000,265500.0,0.0000,0.0215,2,1.0000,0.0000,1.0000,NaN,0.0000,0
29047,202608,54530,"hawkins, wi",297500.0,0.0000,2.1349,3,-0.1429,0.5000,59.0,1.2056,-0.2436,0,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,0.0000,0.0000,0.0000,2.0,NaN,1.0000,127.0,-0.1443,-0.5646,1443.0,0.4430,1.2494,244967.0,-0.0126,1.5813,4,0.1429,0.3333,0.6667,NaN,0.1667,1
29048,202608,35755,"langston, al",574500.0,0.1011,-0.2584,12,0.0000,1.0000,115.0,0.2568,0.0177,0,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,4.0,1.0000,NaN,0.2857,0.1190,0.2857,1.0,NaN,0.0000,324.0,-0.0056,0.0763,1950.0,-0.1053,-0.4569,725423.0,0.0650,-0.3124,14,0.1667,1.0000,0.0833,NaN,-0.0833,1
29049,202608,69148,"lisco, ne",98700.0,0.0000,-0.7005,1,0.0000,0.0000,107.0,0.2456,5.2647,0,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,0.0000,0.0000,0.0000,1.0,NaN,NaN,40.0,0.0000,-0.7855,2440.0,0.0000,0.3967,98700.0,0.0000,-0.7005,1,0.0000,0.0000,1.0000,NaN,NaN,1
29050,202608,95459,"manchester, ca",1206250.0,-0.1904,0.5366,12,0.0909,0.2000,148.0,0.2156,0.4300,0,NaN,-1.0,0,NaN,NaN,0.0,0.0,0.0,0.0,-1.0000,NaN,0.0000,-0.5455,0.0000,1.0,NaN,0.0000,430.0,-0.0670,-0.2137,1678.0,-0.0868,0.0102,2114242.0,-0.0613,0.0235,12,0.0909,0.0909,0.0833,NaN,-0.0167,1

## Filter the national data down to Florida, Central Florida, and Orlando (August 2026, and Historical)

In [4]:
current_data = august.copy()
past_data = historical.copy()

In [5]:
# greater central forida zips 
orlando_orange_county = [
    "32801", "32803", "32804", "32805", "32806", "32808", "32810",
    "32807", "32817", "32826", "32819", "32828", "32827", "32832", 
    "32835", "32703", "32704", "32712", "34761", "34787", "34786"
]
orlando_orange_county = list(map(int, orlando_orange_county))

seminole_county = [
    "32701", "32714", "32750", "32779", "32746", "32771", 
    "32772", "32773", "32707", "32708", "32765", "32766"
]
seminole_county = list(map(int, seminole_county))

osceola_county = [
    "34741", "34743", "34744", "34746", "34747", "34758",
    "34769", "34770", "34771", "34772"
]
osceola_county = list(map(int, osceola_county))

central_fl_tri_county = orlando_orange_county + seminole_county + osceola_county

In [6]:
def filterToFlorida(df):
    '''pass the national level data here to filter just to the state of florida '''
    florida = df.copy()
    florida[['city', 'state']] = florida['zip_name'].str.split(',', expand=True)
    florida['state'] = florida['state'].str.strip()
    florida['city'] = florida['city'].str.strip()
    florida = florida[florida['state'] == 'fl'] #we've filtered down to florida! 
    return florida 

# central_fl = orl[orl['postal_code'].isin(central_fl_tri_county)]
# orl = orl[orl['postal_code'].isin(orlando_orange_county)]
def filterToCentralFlorida(df):
        '''pass the florida level data here to filter just to central florida and further filter to orlando '''
        central_fl_df = df[df['postal_code'].isin(central_fl_tri_county)] 
        orlando_df = central_fl_df[central_fl_df['postal_code'].isin(orlando_orange_county)]
        return central_fl_df, orlando_df

In [7]:

fl_august = filterToFlorida(current_data)  # current florida august data 
fl_historical =  filterToFlorida(past_data) # past florida data 

central_fl_august, orl_august = filterToCentralFlorida(fl_august) #current central florida and orlando data 
central_fl_historical, orl_historical = filterToCentralFlorida(fl_historical) #past central florida and orlando data

### Check to make sure everything has been filtered properly

In [8]:
print(f"---Current Florida State Data--- \n Unique States:{fl_august['state'].unique()}\n Date:{fl_august['month_date_yyyymm'].unique()}\n # of Cities: {fl_august['zip_name'].nunique()}\n")
print(f"---Historical Florida State Data--- \n Unique States:{fl_historical['state'].unique()}\n Date:{fl_historical['month_date_yyyymm'].unique()}\n # of Cities: {fl_historical['zip_name'].nunique()}\n")

---Current Florida State Data---
 Unique States:['fl']
 Date:[202608]
 # of Cities: 418

---Historical Florida State Data---
 Unique States:['fl']
 Date:[202608 202607 202606 202605 202604 202603 202602 202601 202512 202511
 202510 202509 202508 202507 202506 202505 202504 202503 202502 202501
 202412 202411 202410 202409 202408 202407 202406 202405 202404 202403
 202402 202401 202312 202311 202310 202309 202308 202307 202306 202305
 202304 202303 202302 202301 202212 202211 202210 202209 202208 202207
 202206 202205 202204 202203 202202 202201 202112 202111 202110 202109
 202108 202107 202106 202105 202104 202103 202102 202101 202012 202011
 202010 202009 202008 202007 202006 202005 202004 202003 202002 202001
 201912 201911 201910 201909 201908 201907 201906 201905 201904 201903
 201902 201901 201812 201811 201810 201809 201808 201807 201806 201805
 201804 201803 201802 201801 201712 201711 201710 201709 201708 201707
 201706 201705 201704 201703 201702 201701 201612 201611 201610 201609
 201608 201607]
 # of Cities: 429

In [9]:
print(f"---Current Central Florida Data--- \n Unique States:{central_fl_august['state'].unique()}\n Date:{central_fl_august['month_date_yyyymm'].unique()}\n # of Cities: {central_fl_august['zip_name'].nunique()}\n")
print(f"---Historical Central Florida Data--- \n Unique States:{central_fl_historical['state'].unique()}\n Date:{central_fl_historical['month_date_yyyymm'].unique()}\n # of Cities: {central_fl_historical['zip_name'].nunique()}\n")

---Current Central Florida Data---
 Unique States:['fl']
 Date:[202608]
 # of Cities: 14

---Historical Central Florida Data---
 Unique States:['fl']
 Date:[202608 202607 202606 202605 202604 202603 202602 202601 202512 202511
 202510 202509 202508 202507 202506 202505 202504 202503 202502 202501
 202412 202411 202410 202409 202408 202407 202406 202405 202404 202403
 202402 202401 202312 202311 202310 202309 202308 202307 202306 202305
 202304 202303 202302 202301 202212 202211 202210 202209 202208 202207
 202206 202205 202204 202203 202202 202201 202112 202111 202110 202109
 202108 202107 202106 202105 202104 202103 202102 202101 202012 202011
 202010 202009 202008 202007 202006 202005 202004 202003 202002 202001
 201912 201911 201910 201909 201908 201907 201906 201905 201904 201903
 201902 201901 201812 201811 201810 201809 201808 201807 201806 201805
 201804 201803 201802 201801 201712 201711 201710 201709 201708 201707
 201706 201705 201704 201703 201702 201701 201612 201611 201610 201609
 201608 201607]
 # of Cities: 14

In [10]:
print(f"---Current Orlando Data---  \n Unique States:{orl_august['state'].unique()}\n Date:{orl_august['month_date_yyyymm'].unique()}\n # of Cities: {orl_august['zip_name'].nunique()}\n")
print(f"---Historical Orlando Data---  \n Unique States:{orl_historical['state'].unique()}\n Date:{orl_historical['month_date_yyyymm'].unique()}\n # of Cities: {orl_historical['zip_name'].nunique()}\n")

---Current Orlando Data---
 Unique States:['fl']
 Date:[202608]
 # of Cities: 5

---Historical Orlando Data---
 Unique States:['fl']
 Date:[202608 202607 202606 202605 202604 202603 202602 202601 202512 202511
 202510 202509 202508 202507 202506 202505 202504 202503 202502 202501
 202412 202411 202410 202409 202408 202407 202406 202405 202404 202403
 202402 202401 202312 202311 202310 202309 202308 202307 202306 202305
 202304 202303 202302 202301 202212 202211 202210 202209 202208 202207
 202206 202205 202204 202203 202202 202201 202112 202111 202110 202109
 202108 202107 202106 202105 202104 202103 202102 202101 202012 202011
 202010 202009 202008 202007 202006 202005 202004 202003 202002 202001
 201912 201911 201910 201909 201908 201907 201906 201905 201904 201903
 201902 201901 201812 201811 201810 201809 201808 201807 201806 201805
 201804 201803 201802 201801 201712 201711 201710 201709 201708 201707
 201706 201705 201704 201703 201702 201701 201612 201611 201610 201609
 201608 201607]
 # of Cities: 5

### Filter down to zips that Jeanine serves

In [11]:
focus_zips = [34786, 34787, 34761, 32712 , 32703, 32801] #jeanine's target market
alcime = central_fl_historical[central_fl_historical['postal_code'].isin(focus_zips)]
alcime

,month_date_yyyymm,postal_code,zip_name,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,median_days_on_market_mm,median_days_on_market_yy,new_listing_count,new_listing_count_mm,new_listing_count_yy,price_increased_count,price_increased_count_mm,price_increased_count_yy,price_increased_share,price_increased_share_mm,price_increased_share_yy,price_reduced_count,price_reduced_count_mm,price_reduced_count_yy,price_reduced_share,price_reduced_share_mm,price_reduced_share_yy,pending_listing_count,pending_listing_count_mm,pending_listing_count_yy,median_listing_price_per_square_foot,median_listing_price_per_square_foot_mm,median_listing_price_per_square_foot_yy,median_square_feet,median_square_feet_mm,median_square_feet_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag,city,state
8183,202608,32712,"apopka, fl",455000.0,-0.0246,-0.0712,259,0.0058,0.0792,72.0,0.0511,0.1901,72,-0.2800,-0.1000,4,-0.3333,-0.5,0.0080,-0.0034,-0.0104,124.0,0.2917,0.2400,0.2650,0.0797,0.0351,154.0,0.0233,0.3162,207.0,-0.0006,-0.0519,2077.0,0.0000,-0.0699,494250.0,-0.0276,-0.0921,411,0.0074,0.1743,0.5946,0.0101,0.1071,0.0,apopka,fl
9079,202608,34761,"ocoee, fl",438000.0,0.0368,-0.0374,137,0.0186,0.1513,68.0,0.0837,0.1930,44,-0.1200,-0.0833,0,NaN,-1.0,0.0000,0.0000,-0.0161,68.0,0.2593,0.1333,0.2595,0.0620,-0.0071,76.0,0.0000,0.0857,219.0,-0.0029,-0.0401,1915.0,0.0606,-0.0103,465740.0,0.0446,-0.0939,215,0.0190,0.1436,0.5547,-0.0103,-0.0335,0.0,ocoee,fl
17845,202608,34787,"winter garden, fl",590000.0,0.0022,-0.0407,639,-0.0244,-0.0169,72.0,0.0909,0.0000,204,-0.0642,0.1087,8,1.0000,1.0,0.0072,0.0038,0.0031,260.0,0.0078,0.1207,0.2226,0.0166,-0.0081,326.0,-0.0151,0.7814,256.0,0.0029,-0.0187,2204.0,-0.0011,-0.0541,708634.0,-0.0095,-0.0506,960,-0.0264,0.1622,0.5102,0.0048,0.2286,0.0,winter garden,fl
19739,202608,34786,"windermere, fl",1089000.0,-0.0200,0.1204,233,-0.0251,-0.0567,75.0,0.0714,0.1364,56,-0.3171,-0.1250,0,NaN,-1.0,0.0000,0.0000,-0.0099,84.0,-0.0233,0.0000,0.2353,0.0229,0.0165,79.0,0.0128,-0.0482,341.0,-0.0136,0.0983,3211.0,-0.0170,0.0368,2272980.0,-0.0055,0.3265,310,-0.0143,-0.0520,0.3391,0.0127,0.0030,0.0,windermere,fl
19757,202608,32703,"apopka, fl",405000.0,0.0095,0.0387,169,0.0563,-0.0398,66.0,0.0820,0.1000,68,0.1724,0.0000,4,1.0000,0.0,0.0130,0.0077,0.0021,92.0,0.1500,0.0952,0.2779,0.0452,0.0218,97.0,-0.1745,-0.1416,219.0,-0.0118,-0.0087,1844.0,0.0216,0.0395,446249.0,0.0080,0.0266,263,-0.0573,-0.0993,0.5740,-0.1604,-0.0681,0.0,apopka,fl
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3424422,201607,34786,"windermere, fl",641256.0,NaN,NaN,558,NaN,NaN,81.0,NaN,NaN,144,NaN,NaN,24,NaN,NaN,0.0288,NaN,NaN,162.0,NaN,NaN,0.1818,NaN,NaN,156.0,NaN,NaN,183.0,NaN,NaN,3527.0,NaN,NaN,1141180.0,NaN,NaN,709,NaN,NaN,0.2789,NaN,NaN,NaN,windermere,fl
3424815,201607,32703,"apopka, fl",239000.0,NaN,NaN,125,NaN,NaN,43.0,NaN,NaN,88,NaN,NaN,14,NaN,NaN,0.0411,NaN,NaN,38.0,NaN,NaN,0.1074,NaN,NaN,141.0,NaN,NaN,111.0,NaN,NaN,1995.0,NaN,NaN,261231.0,NaN,NaN,266,NaN,NaN,1.1325,NaN,NaN,NaN,apopka,fl
3428521,201607,34787,"winter garden, fl",360305.0,NaN,NaN,397,NaN,NaN,61.0,NaN,NaN,158,NaN,NaN,38,NaN,NaN,0.0495,NaN,NaN,176.0,NaN,NaN,0.2328,NaN,NaN,215.0,NaN,NaN,134.0,NaN,NaN,2811.0,NaN,NaN,428933.0,NaN,NaN,610,NaN,NaN,0.5403,NaN,NaN,NaN,winter garden,fl
3443616,201607,32801,"orlando, fl",332548.0,NaN,NaN,138,NaN,NaN,72.0,NaN,NaN,32,NaN,NaN,0,NaN,NaN,0.0000,NaN,NaN,50.0,NaN,NaN,0.2005,NaN,NaN,62.0,NaN,NaN,260.0,NaN,NaN,1263.0,NaN,NaN,404568.0,NaN,NaN,199,NaN,NaN,0.4457,NaN,NaN,NaN,orlando,fl
3443974,201607,32712,"apopka, fl",298500.0,NaN,NaN,166,NaN,NaN,56.0,NaN,NaN,82,NaN,NaN,12,NaN,NaN,0.0307,NaN,NaN,80.0,NaN,NaN,0.1789,NaN,NaN,151.0,NaN,NaN,114.0,NaN,NaN,2645.0,NaN,NaN,304765.0,NaN,NaN,318,NaN,NaN,0.9066,NaN,NaN,NaN,apopka,fl

We have filtered down to some key dataframes

HISTORICAL DATA
- `fl_historical`
- `central_fl_historical`
- `orl_historical`

AUGUST 2026 DATA
- `fl_august`
- `central_fl_august`
- `orl_august`


`Alcime`: data for the zips Jeanine Serves

So now that we have the current data, historical data (and both for only the zips Jeanine serves) we can:

- Keep: month, zip, active listings, price-reduced count, median days on market, pending ratio, median list price and 
- Check for missing months; drop zips with very few listings (document the cutoff)

And compare the current numbers with historical numbers

# Core Metrics

3 core metrics to determine if a real estate market is seller-favored, balanced, or buyer-favored:

1. Months of Inventory: `Active Listings / Monthly Sales = Months of Inventory`

	Calculates how long it would take for all current homes on the market to sell at the current pace of sales if no new homes were listed.

- The Benchmarks:
	- Seller’s Market: Less than 4 months of inventory. Supply is low, and buyers are competing.
	- Balanced Market: 4 to 6 months of inventory. Supply matches demand reasonably well.
	- Buyer’s Market: More than 6 months of inventory. Supply is high, giving buyers the upper hand.


2. Days On Market (DOM) and Sale-to-List Price Ratio

	Must look at how quickly homes move and how much leverage sellers have during negotiations

	- Days on Market (DOM):
		- Seller-Favored: DOM is steadily decreasing or historically low (e.g., under 30 days).
		- Buyer-Favored: DOM is steadily increasing or high (e.g., over 60–90 days).
 	- Sale-to-List Price Ratio:
		-  Seller-Favored: The ratio is close to or above 100%, meaning homes sell at or above asking price.
		- Buyer-Favored: The ratio drops below 95%, showing that sellers are accepting steep discounts.


3. Year-over-Year Velocity

	Real estate is highly seasonal (spring is usually busier than winter). To avoid seasonal confusion, compare the current month's data to the same month in previous years.

	- Seller-Favored Shift: If this October has fewer active listings and higher median prices than last October, the zip code is moving deeper into a seller's market.
	- Buyer-Favored Shift: If active listings are spiking and price growth is flatlining or turning negative compared to the same time last year, the market is shifting toward buyers.

# Data Profiling

now we enter the cleaning -> eda -> further cleaning process

In [12]:
orl_historical.reset_index(inplace=True)
#one row = one zip code within the greater orlando area's monthly data 0 median price, pending listings, tital listings, etc
# why are some like median_listing_price_yy or median_listing_price_mm tiny decimals?

In [13]:
orl_historical.info() # is the august data folded in to the historical data? 
orl_historical.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2440 entries, 0 to 2439
Data columns (total 49 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   index                                    2440 non-null   int64
 1   month_date_yyyymm                        2440 non-null   int64
 2   postal_code                              2440 non-null   int64
 3   zip_name                                 2440 non-null   object
 4   median_listing_price                     2440 non-null   float64
 5   median_listing_price_mm                  2200 non-null   float64
 6   median_listing_price_yy                  2200 non-null   float64
 7   active_listing_count                     2440 non-null   int64
 8   active_listing_count_mm                  2200 non-null   float64
 9   active_listing_count_yy                  2200 non-null   float64
 10  median_days_on_market                    2440 non-null   float64
 11  median_days_on_market_mm                 2200 non-null   float64
 12  median_days_on_market_yy                 2200 non-null   float64
 13  new_listing_count                        2440 non-null   int64
 14  new_listing_count_mm                     2200 non-null   float64
 15  new_listing_count_yy                     2200 non-null   float64
 16  price_increased_count                    2440 non-null   int64
 17  price_increased_count_mm                 1195 non-null   float64
 18  price_increased_count_yy                 1300 non-null   float64
 19  price_increased_share                    2440 non-null   float64
 20  price_increased_share_mm                 2200 non-null   float64
 21  price_increased_share_yy                 2200 non-null   float64
 22  price_reduced_count                      2440 non-null   float64
 23  price_reduced_count_mm                   2184 non-null   float64
 24  price_reduced_count_yy                   2184 non-null   float64
 25  price_reduced_share                      2440 non-null   float64
 26  price_reduced_share_mm                   2200 non-null   float64
 27  price_reduced_share_yy                   2200 non-null   float64
 28  pending_listing_count                    2440 non-null   float64
 29  pending_listing_count_mm                 2200 non-null   float64
 30  pending_listing_count_yy                 2200 non-null   float64
 31  median_listing_price_per_square_foot     2440 non-null   float64
 32  median_listing_price_per_square_foot_mm  2200 non-null   float64
 33  median_listing_price_per_square_foot_yy  2200 non-null   float64
 34  median_square_feet                       2440 non-null   float64
 35  median_square_feet_mm                    2200 non-null   float64
 36  median_square_feet_yy                    2200 non-null   float64
 37  average_listing_price                    2440 non-null   float64
 38  average_listing_price_mm                 2200 non-null   float64
 39  average_listing_price_yy                 2200 non-null   float64
 40  total_listing_count                      2440 non-null   int64
 41  total_listing_count_mm                   2200 non-null   float64
 42  total_listing_count_yy                   2200 non-null   float64
 43  pending_ratio                            2440 non-null   float64
 44  pending_ratio_mm                         2200 non-null   float64
 45  pending_ratio_yy                         2200 non-null   float64
 46  quality_flag                             2200 non-null   float64
 47  city                                     2440 non-null   object
 48  state                                    2440 non-null   object
dtypes: float64(39), int64(7), object(3)
memory usage: 934.2+ KB

(2440, 49)

In [14]:
orl_historical.rename(columns={'month_date_yyyymm':'month_year'}, inplace=True)

/var/folders/cm/46nnvpl978b_vb10b1dp7rp80000gn/T/ipykernel_98200/1807519895.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orl_historical.rename(columns={'month_date_yyyymm':'month_year'}, inplace=True)

In [15]:
# lets create a function that spits out month_year as 2 columns: month and year 
def split_monthYear(month_year):
    ''' create a function that spits out month_year as 2 columns: month and year ''' 
    string_monthYear = month_year.astype(str)
    year = string_monthYear.str[:4].astype(int)
    month = string_monthYear.str[4:].astype(int)
    return pd.DataFrame({'year': year, 'month': month}, index=month_year.index)

orl_historical[['year', 'month']] = split_monthYear(orl_historical['month_year'])
orl_historical

/var/folders/cm/46nnvpl978b_vb10b1dp7rp80000gn/T/ipykernel_98200/3031955848.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orl_historical[['year', 'month']] = split_monthYear(orl_historical['month_year'])
/var/folders/cm/46nnvpl978b_vb10b1dp7rp80000gn/T/ipykernel_98200/3031955848.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orl_historical[['year', 'month']] = split_monthYear(orl_historical['month_year'])

,index,month_year,postal_code,zip_name,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,median_days_on_market_mm,median_days_on_market_yy,new_listing_count,new_listing_count_mm,new_listing_count_yy,price_increased_count,price_increased_count_mm,price_increased_count_yy,price_increased_share,price_increased_share_mm,price_increased_share_yy,price_reduced_count,price_reduced_count_mm,price_reduced_count_yy,price_reduced_share,price_reduced_share_mm,price_reduced_share_yy,pending_listing_count,pending_listing_count_mm,pending_listing_count_yy,median_listing_price_per_square_foot,median_listing_price_per_square_foot_mm,median_listing_price_per_square_foot_yy,median_square_feet,median_square_feet_mm,median_square_feet_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag,city,state,year,month
0,7162,202608,32828,"orlando, fl",489450.0,-0.0056,0.0136,187,0.0418,0.2897,65.0,0.1017,0.1504,60,-0.2500,0.2500,0,-1.0000,NaN,0.0000,-0.0116,0.0000,100.0,0.3158,0.3158,0.3003,0.0681,-0.0217,62.0,-0.1448,0.3778,224.0,0.0033,-0.0366,2083.0,-0.0305,0.0462,474980.0,-0.0103,-0.0550,252,0.0000,0.3194,0.3316,-0.0723,0.0212,0.0,orlando,fl,2026,8
1,8183,202608,32712,"apopka, fl",455000.0,-0.0246,-0.0712,259,0.0058,0.0792,72.0,0.0511,0.1901,72,-0.2800,-0.1000,4,-0.3333,-0.5,0.0080,-0.0034,-0.0104,124.0,0.2917,0.2400,0.2650,0.0797,0.0351,154.0,0.0233,0.3162,207.0,-0.0006,-0.0519,2077.0,0.0000,-0.0699,494250.0,-0.0276,-0.0921,411,0.0074,0.1743,0.5946,0.0101,0.1071,0.0,apopka,fl,2026,8
2,9079,202608,34761,"ocoee, fl",438000.0,0.0368,-0.0374,137,0.0186,0.1513,68.0,0.0837,0.1930,44,-0.1200,-0.0833,0,NaN,-1.0,0.0000,0.0000,-0.0161,68.0,0.2593,0.1333,0.2595,0.0620,-0.0071,76.0,0.0000,0.0857,219.0,-0.0029,-0.0401,1915.0,0.0606,-0.0103,465740.0,0.0446,-0.0939,215,0.0190,0.1436,0.5547,-0.0103,-0.0335,0.0,ocoee,fl,2026,8
3,10275,202608,32803,"orlando, fl",570000.0,-0.0150,0.1692,88,-0.0112,-0.1927,54.0,0.0693,-0.1818,40,0.0526,-0.1667,0,NaN,NaN,0.0000,0.0000,0.0000,36.0,-0.0526,-0.1000,0.2543,0.0470,0.0543,36.0,0.1077,-0.1818,362.0,0.0038,0.0593,1839.0,0.0068,0.3007,822287.0,0.0313,0.3269,125,0.0246,-0.1554,0.4091,0.0439,0.0054,0.0,orlando,fl,2026,8
4,10898,202608,32835,"orlando, fl",249950.0,-0.0002,0.0161,218,-0.1138,-0.2829,80.0,0.1080,-0.0756,52,-0.1875,0.1818,4,0.0000,NaN,0.0125,0.0016,0.0125,68.0,-0.1053,-0.1905,0.1960,-0.0206,-0.0268,57.0,0.2258,0.2955,194.0,0.0062,-0.0298,1408.0,0.0000,0.0957,392863.0,-0.0126,0.1963,273,-0.0586,-0.2178,0.2615,0.0724,0.1167,0.0,orlando,fl,2026,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2435,3444843,201607,32827,"orlando, fl",509560.0,NaN,NaN,135,NaN,NaN,72.0,NaN,NaN,30,NaN,NaN,6,NaN,NaN,0.0290,NaN,NaN,26.0,NaN,NaN,0.1164,NaN,NaN,46.0,NaN,NaN,187.0,NaN,NaN,2853.0,NaN,NaN,827654.0,NaN,NaN,182,NaN,NaN,0.3407,NaN,NaN,NaN,orlando,fl,2016,7
2436,3449909,201607,32826,"orlando, fl",250975.0,NaN,NaN,42,NaN,NaN,35.0,NaN,NaN,42,NaN,NaN,0,NaN,NaN,0.0000,NaN,NaN,16.0,NaN,NaN,0.1432,NaN,NaN,47.0,NaN,NaN,122.0,NaN,NaN,2179.0,NaN,NaN,266435.0,NaN,NaN,88,NaN,NaN,1.1205,NaN,NaN,NaN,orlando,fl,2016,7
2437,3449970,201607,32806,"orlando, fl",323675.0,NaN,NaN,127,NaN,NaN,44.0,NaN,NaN,76,NaN,NaN,4,NaN,NaN,0.0136,NaN,NaN,60.0,NaN,NaN,0.2179,NaN,NaN,93.0,NaN,NaN,172.0,NaN,NaN,1918.0,NaN,NaN,412155.0,NaN,NaN,219,NaN,NaN,0.7312,NaN,NaN,NaN,orlando,fl,2016,7
2438,3450785,201607,32828,"orlando, fl",282350.0,NaN,NaN,198,NaN,NaN,42.0,NaN,NaN,134,NaN,NaN,4,NaN,NaN,0.0075,NaN,NaN,114.0,NaN,NaN,0.2094,NaN,NaN,187.0,NaN,NaN,122.0,NaN,NaN,2380.0,NaN,NaN,298888.0,NaN,NaN,385,NaN,NaN,0.9444,NaN,NaN,NaN,orlando,fl,2016,7
2439,3451835,201607,32810,"orlando, fl",147000.0,NaN,NaN,88,NaN,NaN,31.0,NaN,NaN,64,NaN,NaN,6,NaN,NaN,0.0263,NaN,NaN,40.0,NaN,NaN,0.1542,NaN,NaN,90.0,NaN,NaN,100.0,NaN,NaN,1350.0,NaN,NaN,151563.0,NaN,NaN,177,NaN,NaN,1.0286,NaN,NaN,NaN,orlando,fl,2016,7

In [20]:
orl_historical.isna().sum() #240 to 256ish, some at 1140+ - total of 8897

index                                         0
month_year                                    0
postal_code                                   0
zip_name                                      0
median_listing_price                          0
median_listing_price_mm                     240
median_listing_price_yy                     240
active_listing_count                          0
active_listing_count_mm                     240
active_listing_count_yy                     240
median_days_on_market                         0
median_days_on_market_mm                    240
median_days_on_market_yy                    240
new_listing_count                             0
new_listing_count_mm                        240
new_listing_count_yy                        240
price_increased_count                         0
price_increased_count_mm                   1245
price_increased_count_yy                   1140
price_increased_share                         0
price_increased_share_mm                    240
price_increased_share_yy                    240
price_reduced_count                           0
price_reduced_count_mm                      256
price_reduced_count_yy                      256
price_reduced_share                           0
price_reduced_share_mm                      240
price_reduced_share_yy                      240
pending_listing_count                         0
pending_listing_count_mm                    240
pending_listing_count_yy                    240
median_listing_price_per_square_foot          0
median_listing_price_per_square_foot_mm     240
median_listing_price_per_square_foot_yy     240
median_square_feet                            0
median_square_feet_mm                       240
median_square_feet_yy                       240
average_listing_price                         0
average_listing_price_mm                    240
average_listing_price_yy                    240
total_listing_count                           0
total_listing_count_mm                      240
total_listing_count_yy                      240
pending_ratio                                 0
pending_ratio_mm                            240
pending_ratio_yy                            240
quality_flag                                240
city                                          0
state                                         0
year                                          0
month                                         0
dtype: int64

In [17]:
orl_historical.duplicated().sum() # no duplicate rows!

np.int64(0)

In [23]:
# explore the nulls, and do a little eda (summary statistics and visualizations to spot patterns, trends, and hidden anomalies)
orl_historical[orl_historical['price_increased_count_mm'].isna()]

,index,month_year,postal_code,zip_name,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,median_days_on_market_mm,median_days_on_market_yy,new_listing_count,new_listing_count_mm,new_listing_count_yy,price_increased_count,price_increased_count_mm,price_increased_count_yy,price_increased_share,price_increased_share_mm,price_increased_share_yy,price_reduced_count,price_reduced_count_mm,price_reduced_count_yy,price_reduced_share,price_reduced_share_mm,price_reduced_share_yy,pending_listing_count,pending_listing_count_mm,pending_listing_count_yy,median_listing_price_per_square_foot,median_listing_price_per_square_foot_mm,median_listing_price_per_square_foot_yy,median_square_feet,median_square_feet_mm,median_square_feet_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag,city,state,year,month
2,9079,202608,34761,"ocoee, fl",438000.0,0.0368,-0.0374,137,0.0186,0.1513,68.0,0.0837,0.1930,44,-0.1200,-0.0833,0,NaN,-1.0,0.0000,0.0,-0.0161,68.0,0.2593,0.1333,0.2595,0.0620,-0.0071,76.0,0.0000,0.0857,219.0,-0.0029,-0.0401,1915.0,0.0606,-0.0103,465740.0,0.0446,-0.0939,215,0.0190,0.1436,0.5547,-0.0103,-0.0335,0.0,ocoee,fl,2026,8
3,10275,202608,32803,"orlando, fl",570000.0,-0.0150,0.1692,88,-0.0112,-0.1927,54.0,0.0693,-0.1818,40,0.0526,-0.1667,0,NaN,NaN,0.0000,0.0,0.0000,36.0,-0.0526,-0.1000,0.2543,0.0470,0.0543,36.0,0.1077,-0.1818,362.0,0.0038,0.0593,1839.0,0.0068,0.3007,822287.0,0.0313,0.3269,125,0.0246,-0.1554,0.4091,0.0439,0.0054,0.0,orlando,fl,2026,8
6,19154,202608,32819,"orlando, fl",525000.0,-0.0223,-0.0278,198,-0.0025,-0.1646,87.0,-0.0389,0.0813,44,0.0000,-0.2667,0,NaN,NaN,0.0000,0.0,0.0000,64.0,0.1034,-0.1111,0.2162,0.0177,0.0174,37.0,-0.0976,-0.1957,308.0,-0.0025,-0.0156,1756.0,-0.0168,-0.0330,748189.0,-0.0606,0.0056,235,-0.0208,-0.1840,0.1869,-0.0197,-0.0072,0.0,orlando,fl,2026,8
8,19739,202608,34786,"windermere, fl",1089000.0,-0.0200,0.1204,233,-0.0251,-0.0567,75.0,0.0714,0.1364,56,-0.3171,-0.1250,0,NaN,-1.0,0.0000,0.0,-0.0099,84.0,-0.0233,0.0000,0.2353,0.0229,0.0165,79.0,0.0128,-0.0482,341.0,-0.0136,0.0983,3211.0,-0.0170,0.0368,2272980.0,-0.0055,0.3265,310,-0.0143,-0.0520,0.3391,0.0127,0.0030,0.0,windermere,fl,2026,8
10,19855,202608,32817,"orlando, fl",417500.0,-0.0430,-0.1278,53,-0.0702,-0.2090,50.0,0.1364,-0.3789,24,-0.2500,0.2000,0,NaN,NaN,0.0000,0.0,0.0000,28.0,0.2727,-0.2222,0.2545,0.0616,-0.0788,25.0,-0.2424,-0.1935,247.0,-0.0234,-0.0416,1628.0,-0.0431,-0.1425,421769.0,-0.1297,-0.2889,78,-0.1086,-0.2041,0.4717,-0.1072,0.0090,1.0,orlando,fl,2026,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2435,3444843,201607,32827,"orlando, fl",509560.0,NaN,NaN,135,NaN,NaN,72.0,NaN,NaN,30,NaN,NaN,6,NaN,NaN,0.0290,NaN,NaN,26.0,NaN,NaN,0.1164,NaN,NaN,46.0,NaN,NaN,187.0,NaN,NaN,2853.0,NaN,NaN,827654.0,NaN,NaN,182,NaN,NaN,0.3407,NaN,NaN,NaN,orlando,fl,2016,7
2436,3449909,201607,32826,"orlando, fl",250975.0,NaN,NaN,42,NaN,NaN,35.0,NaN,NaN,42,NaN,NaN,0,NaN,NaN,0.0000,NaN,NaN,16.0,NaN,NaN,0.1432,NaN,NaN,47.0,NaN,NaN,122.0,NaN,NaN,2179.0,NaN,NaN,266435.0,NaN,NaN,88,NaN,NaN,1.1205,NaN,NaN,NaN,orlando,fl,2016,7
2437,3449970,201607,32806,"orlando, fl",323675.0,NaN,NaN,127,NaN,NaN,44.0,NaN,NaN,76,NaN,NaN,4,NaN,NaN,0.0136,NaN,NaN,60.0,NaN,NaN,0.2179,NaN,NaN,93.0,NaN,NaN,172.0,NaN,NaN,1918.0,NaN,NaN,412155.0,NaN,NaN,219,NaN,NaN,0.7312,NaN,NaN,NaN,orlando,fl,2016,7
2438,3450785,201607,32828,"orlando, fl",282350.0,NaN,NaN,198,NaN,NaN,42.0,NaN,NaN,134,NaN,NaN,4,NaN,NaN,0.0075,NaN,NaN,114.0,NaN,NaN,0.2094,NaN,NaN,187.0,NaN,NaN,122.0,NaN,NaN,2380.0,NaN,NaN,298888.0,NaN,NaN,385,NaN,NaN,0.9444,NaN,NaN,NaN,orlando,fl,2016,7
2439,3451835,201607,32810,"orlando, fl",147000.0,NaN,NaN,88,NaN,NaN,31.0,NaN,NaN,64,NaN,NaN,6,NaN,NaN,0.0263,NaN,NaN,40.0,NaN,NaN,0.1542,NaN,NaN,90.0,NaN,NaN,100.0,NaN,NaN,1350.0,NaN,NaN,151563.0,NaN,NaN,177,NaN,NaN,1.0286,NaN,NaN,NaN,orlando,fl,2016,7