# Business Goal/Outcome

## Goal
Give a realtor like Jeanine a data-backed answer to the question every seller asks ("What's my home worth, and how long will it take?") and every buyer asks ("Do I have room to negotiate?"), specific to the zip they're standing in.

## Outcomes
- Realtor can price the seller correctly in listing appts 
- Aide buyer consolutations and negotiation strategy
- Help with prospecting and knowing which zips to farm
- Data to feed market update content
- Help relay market expertise

# Research Question
Where in Orlando have sellers lost leverage since 2023, and where do they still have it?

# Hypothesis

**H1: New construction hurt resale sellers most.**  
		In 34787 and 32712, price cut share and days on market will have risen more than the metro average since 2022, because builders' incentives pull buyers away from resale homes.  
		_Rejected if:_ both zips' increases are at or below the metro average.


**H2: Windermere held up.**  
		In 34786, the leverage score will have dropped less than the metro average since 2022, because scarce lakefront and large-lot homes and less rate-sensitive buyers protect sellers.  
		_Rejected if:_ 34786's drop is at or above the metro average. If that happens, the Horizon West portion of the zip may be dragging it down.


**H3: Affordable zips**
 34761 and 32703 will have lost less leverage than 34787 and 32712, because they have less new-construction competition. _Rejected if:_ their drop is the same as or larger than the growth zips'.

# Bring in Data

In [128]:
import pandas as pd

In [129]:
historical = pd.read_csv('/Users/medhasubramaniyan/Desktop/GitHub_Repos/orlando-seller-leverage-analysis/data/RDC_Inventory_Core_Metrics_Zip_History.csv')
historical

,month_date_yyyymm,postal_code,zip_name,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,...,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag
0,202608,74003,"bartlesville, ok",150000.0,0.0000,0.0714,45,-0.0722,0.0714,70.0,...,208058.0,-0.0086,0.0436,71,-0.0596,0.1639,0.5778,0.0417,0.1254,0.0
1,202608,61353,"paw paw, il",294450.0,0.0865,0.0711,7,0.2727,0.4000,27.0,...,432643.0,0.2654,0.2023,8,0.3333,0.1429,0.2143,0.0325,-0.3857,1.0
2,202608,35765,"pisgah, al",307950.0,0.0448,0.1322,15,0.0345,0.5000,105.0,...,312969.0,-0.0256,-0.1669,18,0.1613,0.3846,0.1333,0.0644,-0.0667,1.0
3,202608,21664,"secretary, md",349900.0,0.0294,0.0218,2,0.3333,-0.5000,54.0,...,349900.0,0.0294,0.1915,2,-0.3333,-0.5000,0.0000,-0.6667,-0.2500,0.0
4,202608,37221,"nashville, tn",519900.0,-0.0295,-0.0877,235,0.0129,0.0930,64.0,...,742763.0,0.0067,0.0582,312,-0.0473,-0.0064,0.3277,-0.0861,-0.1375,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3452028,201607,8828,"helmetta, nj",218000.0,NaN,NaN,22,NaN,NaN,67.0,...,243027.0,NaN,NaN,22,NaN,NaN,0.0455,NaN,NaN,NaN
3452029,201607,30536,"ellijay, ga",249350.0,NaN,NaN,128,NaN,NaN,86.0,...,309281.0,NaN,NaN,128,NaN,NaN,0.0118,NaN,NaN,NaN
3452030,201607,37863,"pigeon forge, tn",224750.0,NaN,NaN,189,NaN,NaN,115.0,...,283587.0,NaN,NaN,226,NaN,NaN,0.2042,NaN,NaN,NaN
3452031,201607,32097,"yulee, fl",231973.0,NaN,NaN,150,NaN,NaN,69.0,...,324656.0,NaN,NaN,252,NaN,NaN,0.6923,NaN,NaN,NaN
3452032,201607,59064,"pompeys pillar, mt",199500.0,NaN,NaN,1,NaN,NaN,14.0,...,199500.0,NaN,NaN,1,NaN,NaN,1.0000,NaN,NaN,NaN

In [130]:
august = pd.read_csv('/Users/medhasubramaniyan/Desktop/GitHub_Repos/orlando-seller-leverage-analysis/data/RDC_Inventory_Core_Metrics_Zip.csv')
august

,month_date_yyyymm,postal_code,zip_name,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,...,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag
0,202608,78956,"schulenburg, tx",314000.0,-0.1253,0.0502,28,0.1200,0.4000,124.0,...,410433.0,-0.0986,0.2020,32,0.1228,0.3913,0.1786,0.0386,-0.0214,1
1,202608,30535,"demorest, ga",415000.0,-0.0259,0.0038,55,-0.0090,0.4865,90.0,...,461853.0,-0.0132,0.0613,68,-0.0933,0.4167,0.2545,-0.0878,-0.0428,1
2,202608,83316,"buhl, id",510000.0,0.0000,0.2146,45,-0.0110,-0.0816,79.0,...,699305.0,-0.0023,0.2881,55,-0.0833,-0.1129,0.2222,-0.1184,-0.0635,0
3,202608,94806,"san pablo, ca",577500.0,0.0226,-0.0077,71,0.2034,-0.1013,38.0,...,574916.0,0.0050,-0.0158,91,0.0581,-0.1947,0.3099,-0.1732,-0.1205,0
4,202608,37820,"new market, tn",735000.0,0.0426,0.4703,23,0.1500,0.0455,57.0,...,771742.0,-0.0668,0.5105,29,0.1154,-0.1714,0.3043,-0.0207,-0.1957,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29046,202608,50546,"havelock, ia",265500.0,0.0000,0.0215,1,0.0000,0.0000,81.0,...,265500.0,0.0000,0.0215,2,1.0000,0.0000,1.0000,NaN,0.0000,0
29047,202608,54530,"hawkins, wi",297500.0,0.0000,2.1349,3,-0.1429,0.5000,59.0,...,244967.0,-0.0126,1.5813,4,0.1429,0.3333,0.6667,NaN,0.1667,1
29048,202608,35755,"langston, al",574500.0,0.1011,-0.2584,12,0.0000,1.0000,115.0,...,725423.0,0.0650,-0.3124,14,0.1667,1.0000,0.0833,NaN,-0.0833,1
29049,202608,69148,"lisco, ne",98700.0,0.0000,-0.7005,1,0.0000,0.0000,107.0,...,98700.0,0.0000,-0.7005,1,0.0000,0.0000,1.0000,NaN,NaN,1
29050,202608,95459,"manchester, ca",1206250.0,-0.1904,0.5366,12,0.0909,0.2000,148.0,...,2114242.0,-0.0613,0.0235,12,0.0909,0.0909,0.0833,NaN,-0.0167,1

# Filter the national data down to Florida, Central Florida, and Orlando (August 2026, and Historical)

In [131]:
current_data = august.copy()
past_data = historical.copy()

In [132]:
# greater central forida zips 
orlando_orange_county = [
    "32801", "32803", "32804", "32805", "32806", "32808", "32810",
    "32807", "32817", "32826", "32819", "32828", "32827", "32832", 
    "32835", "32703", "32704", "32712", "34761", "34787", "34786"
]
orlando_orange_county = list(map(int, orlando_orange_county))

seminole_county = [
    "32701", "32714", "32750", "32779", "32746", "32771", 
    "32772", "32773", "32707", "32708", "32765", "32766"
]
seminole_county = list(map(int, seminole_county))

osceola_county = [
    "34741", "34743", "34744", "34746", "34747", "34758",
    "34769", "34770", "34771", "34772"
]
osceola_county = list(map(int, osceola_county))

central_fl_tri_county = orlando_orange_county + seminole_county + osceola_county

In [133]:
def filterToFlorida(df):
    '''pass the national level data here to filter just to the state of florida '''
    florida = df.copy()
    florida[['city', 'state']] = florida['zip_name'].str.split(',', expand=True)
    florida['state'] = florida['state'].str.strip()
    florida['city'] = florida['city'].str.strip()
    florida = florida[florida['state'] == 'fl'] #we've filtered down to florida! 
    return florida 

# central_fl = orl[orl['postal_code'].isin(central_fl_tri_county)]
# orl = orl[orl['postal_code'].isin(orlando_orange_county)]
def filterToCentralFlorida(df):
        '''pass the florida level data here to filter just to central florida and further filter to orlando '''
        central_fl_df = df[df['postal_code'].isin(central_fl_tri_county)] 
        orlando_df = central_fl_df[central_fl_df['postal_code'].isin(orlando_orange_county)]
        return central_fl_df, orlando_df

In [134]:

fl_august = filterToFlorida(current_data)  # current florida august data 
fl_historical =  filterToFlorida(past_data) # past florida data 

central_fl_august, orl_august = filterToCentralFlorida(fl_august) #current central florida and orlando data 
central_fl_historical, orl_historical = filterToCentralFlorida(fl_historical) #past central florida and orlando data

In [135]:
print(f"---Current Florida State Data--- \n Unique States:{fl_august['state'].unique()}\n Date:{fl_august['month_date_yyyymm'].unique()}\n # of Cities: {fl_august['zip_name'].nunique()}\n")
print(f"---Historical Florida State Data--- \n Unique States:{fl_historical['state'].unique()}\n Date:{fl_historical['month_date_yyyymm'].unique()}\n # of Cities: {fl_historical['zip_name'].nunique()}\n")

---Current Florida State Data---
 Unique States:['fl']
 Date:[202608]
 # of Cities: 418

---Historical Florida State Data---
 Unique States:['fl']
 Date:[202608 202607 202606 202605 202604 202603 202602 202601 202512 202511
 202510 202509 202508 202507 202506 202505 202504 202503 202502 202501
 202412 202411 202410 202409 202408 202407 202406 202405 202404 202403
 202402 202401 202312 202311 202310 202309 202308 202307 202306 202305
 202304 202303 202302 202301 202212 202211 202210 202209 202208 202207
 202206 202205 202204 202203 202202 202201 202112 202111 202110 202109
 202108 202107 202106 202105 202104 202103 202102 202101 202012 202011
 202010 202009 202008 202007 202006 202005 202004 202003 202002 202001
 201912 201911 201910 201909 201908 201907 201906 201905 201904 201903
 201902 201901 201812 201811 201810 201809 201808 201807 201806 201805
 201804 201803 201802 201801 201712 201711 201710 201709 201708 201707
 201706 201705 201704 201703 201702 201701 201612 201611 201610 201609
 201608 201607]
 # of Cities: 429

In [136]:
print(f"---Current Central Florida Data--- \n Unique States:{central_fl_august['state'].unique()}\n Date:{central_fl_august['month_date_yyyymm'].unique()}\n # of Cities: {central_fl_august['zip_name'].nunique()}\n")
print(f"---Historical Central Florida Data--- \n Unique States:{central_fl_historical['state'].unique()}\n Date:{central_fl_historical['month_date_yyyymm'].unique()}\n # of Cities: {central_fl_historical['zip_name'].nunique()}\n")

---Current Central Florida Data---
 Unique States:['fl']
 Date:[202608]
 # of Cities: 14

---Historical Central Florida Data---
 Unique States:['fl']
 Date:[202608 202607 202606 202605 202604 202603 202602 202601 202512 202511
 202510 202509 202508 202507 202506 202505 202504 202503 202502 202501
 202412 202411 202410 202409 202408 202407 202406 202405 202404 202403
 202402 202401 202312 202311 202310 202309 202308 202307 202306 202305
 202304 202303 202302 202301 202212 202211 202210 202209 202208 202207
 202206 202205 202204 202203 202202 202201 202112 202111 202110 202109
 202108 202107 202106 202105 202104 202103 202102 202101 202012 202011
 202010 202009 202008 202007 202006 202005 202004 202003 202002 202001
 201912 201911 201910 201909 201908 201907 201906 201905 201904 201903
 201902 201901 201812 201811 201810 201809 201808 201807 201806 201805
 201804 201803 201802 201801 201712 201711 201710 201709 201708 201707
 201706 201705 201704 201703 201702 201701 201612 201611 201610 201609
 201608 201607]
 # of Cities: 14

In [137]:
print(f"---Current Orlando Data---  \n Unique States:{orl_august['state'].unique()}\n Date:{orl_august['month_date_yyyymm'].unique()}\n # of Cities: {orl_august['zip_name'].nunique()}\n")
print(f"---Historical Orlando Data---  \n Unique States:{orl_historical['state'].unique()}\n Date:{orl_historical['month_date_yyyymm'].unique()}\n # of Cities: {orl_historical['zip_name'].nunique()}\n")

---Current Orlando Data---
 Unique States:['fl']
 Date:[202608]
 # of Cities: 5

---Historical Orlando Data---
 Unique States:['fl']
 Date:[202608 202607 202606 202605 202604 202603 202602 202601 202512 202511
 202510 202509 202508 202507 202506 202505 202504 202503 202502 202501
 202412 202411 202410 202409 202408 202407 202406 202405 202404 202403
 202402 202401 202312 202311 202310 202309 202308 202307 202306 202305
 202304 202303 202302 202301 202212 202211 202210 202209 202208 202207
 202206 202205 202204 202203 202202 202201 202112 202111 202110 202109
 202108 202107 202106 202105 202104 202103 202102 202101 202012 202011
 202010 202009 202008 202007 202006 202005 202004 202003 202002 202001
 201912 201911 201910 201909 201908 201907 201906 201905 201904 201903
 201902 201901 201812 201811 201810 201809 201808 201807 201806 201805
 201804 201803 201802 201801 201712 201711 201710 201709 201708 201707
 201706 201705 201704 201703 201702 201701 201612 201611 201610 201609
 201608 201607]
 # of Cities: 5

In [144]:
focus_zips = [34786, 34787, 34761, 32712 , 32703, 32801] #jeanine's target market
alcime = central_fl_historical[central_fl_historical['postal_code'].isin(focus_zips)]
alcime

,month_date_yyyymm,postal_code,zip_name,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,...,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag,city,state
8183,202608,32712,"apopka, fl",455000.0,-0.0246,-0.0712,259,0.0058,0.0792,72.0,...,-0.0921,411,0.0074,0.1743,0.5946,0.0101,0.1071,0.0,apopka,fl
9079,202608,34761,"ocoee, fl",438000.0,0.0368,-0.0374,137,0.0186,0.1513,68.0,...,-0.0939,215,0.0190,0.1436,0.5547,-0.0103,-0.0335,0.0,ocoee,fl
17845,202608,34787,"winter garden, fl",590000.0,0.0022,-0.0407,639,-0.0244,-0.0169,72.0,...,-0.0506,960,-0.0264,0.1622,0.5102,0.0048,0.2286,0.0,winter garden,fl
19739,202608,34786,"windermere, fl",1089000.0,-0.0200,0.1204,233,-0.0251,-0.0567,75.0,...,0.3265,310,-0.0143,-0.0520,0.3391,0.0127,0.0030,0.0,windermere,fl
19757,202608,32703,"apopka, fl",405000.0,0.0095,0.0387,169,0.0563,-0.0398,66.0,...,0.0266,263,-0.0573,-0.0993,0.5740,-0.1604,-0.0681,0.0,apopka,fl
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3424422,201607,34786,"windermere, fl",641256.0,NaN,NaN,558,NaN,NaN,81.0,...,NaN,709,NaN,NaN,0.2789,NaN,NaN,NaN,windermere,fl
3424815,201607,32703,"apopka, fl",239000.0,NaN,NaN,125,NaN,NaN,43.0,...,NaN,266,NaN,NaN,1.1325,NaN,NaN,NaN,apopka,fl
3428521,201607,34787,"winter garden, fl",360305.0,NaN,NaN,397,NaN,NaN,61.0,...,NaN,610,NaN,NaN,0.5403,NaN,NaN,NaN,winter garden,fl
3443616,201607,32801,"orlando, fl",332548.0,NaN,NaN,138,NaN,NaN,72.0,...,NaN,199,NaN,NaN,0.4457,NaN,NaN,NaN,orlando,fl
3443974,201607,32712,"apopka, fl",298500.0,NaN,NaN,166,NaN,NaN,56.0,...,NaN,318,NaN,NaN,0.9066,NaN,NaN,NaN,apopka,fl